// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import (
	"context"
	"testing"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/jaswdr/faker/v2"
	"github.com/stephenafamo/bob"
	models "github.com/tak848/lxgo4-bob/internal/infra/dbgen"
	enums "github.com/tak848/lxgo4-bob/internal/infra/dbgen/dbenums"
)

type ProjectMod interface {
	Apply(context.Context, *ProjectTemplate)
}

type ProjectModFunc func(context.Context, *ProjectTemplate)

func (f ProjectModFunc) Apply(ctx context.Context, n *ProjectTemplate) {
	f(ctx, n)
}

type ProjectModSlice []ProjectMod

func (mods ProjectModSlice) Apply(ctx context.Context, n *ProjectTemplate) {
	for _, f := range mods {
		f.Apply(ctx, n)
	}
}

// ProjectTemplate is an object representing the database table.
// all columns are optional and should be set by mods
type ProjectTemplate struct {
	ID          func() uuid.UUID
	WorkspaceID func() uuid.UUID
	Name        func() string
	Description func() string
	Status      func() enums.ProjectStatus

	r projectR
	f *Factory

	alreadyPersisted bool
}

type projectR struct {
	Workspace *projectRWorkspaceR
	Tasks     []*projectRTasksR
}

type projectRWorkspaceR struct {
	o *WorkspaceTemplate
}
type projectRTasksR struct {
	number int
	o      *TaskTemplate
}

// Apply mods to the ProjectTemplate
func (o *ProjectTemplate) Apply(ctx context.Context, mods ...ProjectMod) {
	for _, mod := range mods {
		mod.Apply(ctx, o)
	}
}

// setModelRels creates and sets the relationships on *models.Project
// according to the relationships in the template. Nothing is inserted into the db
func (t ProjectTemplate) setModelRels(o *models.Project) {
	if t.r.Workspace != nil {
		rel := t.r.Workspace.o.Build()
		rel.R.Projects = append(rel.R.Projects, o)
		o.WorkspaceID = rel.ID // h2
		o.R.Workspace = rel
	}

	if t.r.Tasks != nil {
		rel := models.TaskSlice{}
		for _, r := range t.r.Tasks {
			related := r.o.BuildMany(r.number)
			for _, rel := range related {
				rel.WorkspaceID = o.WorkspaceID // h2
				rel.ProjectID = o.ID            // h2
				rel.R.Project = o
			}
			rel = append(rel, related...)
		}
		o.R.Tasks = rel
	}
}

// BuildSetter returns an *models.ProjectSetter
// this does nothing with the relationship templates
func (o ProjectTemplate) BuildSetter() *models.ProjectSetter {
	m := &models.ProjectSetter{}

	if o.ID != nil {
		val := o.ID()
		m.ID = omit.From(val)
	}
	if o.WorkspaceID != nil {
		val := o.WorkspaceID()
		m.WorkspaceID = omit.From(val)
	}
	if o.Name != nil {
		val := o.Name()
		m.Name = omit.From(val)
	}
	if o.Description != nil {
		val := o.Description()
		m.Description = omit.From(val)
	}
	if o.Status != nil {
		val := o.Status()
		m.Status = omit.From(val)
	}

	return m
}

// BuildManySetter returns an []*models.ProjectSetter
// this does nothing with the relationship templates
func (o ProjectTemplate) BuildManySetter(number int) []*models.ProjectSetter {
	m := make([]*models.ProjectSetter, number)

	for i := range m {
		m[i] = o.BuildSetter()
	}

	return m
}

// Build returns an *models.Project
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ProjectTemplate.Create
func (o ProjectTemplate) Build() *models.Project {
	m := &models.Project{}

	if o.ID != nil {
		m.ID = o.ID()
	}
	if o.WorkspaceID != nil {
		m.WorkspaceID = o.WorkspaceID()
	}
	if o.Name != nil {
		m.Name = o.Name()
	}
	if o.Description != nil {
		m.Description = o.Description()
	}
	if o.Status != nil {
		m.Status = o.Status()
	}

	o.setModelRels(m)

	return m
}

// BuildMany returns an models.ProjectSlice
// Related objects are also created and placed in the .R field
// NOTE: Objects are not inserted into the database. Use ProjectTemplate.CreateMany
func (o ProjectTemplate) BuildMany(number int) models.ProjectSlice {
	m := make(models.ProjectSlice, number)

	for i := range m {
		m[i] = o.Build()
	}

	return m
}

func ensureCreatableProject(m *models.ProjectSetter) {
	if !(m.ID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.ID = omit.From(val)
	}
	if !(m.WorkspaceID.IsValue()) {
		val := random_uuid_UUID(nil)
		m.WorkspaceID = omit.From(val)
	}
	if !(m.Name.IsValue()) {
		val := random_string(nil)
		m.Name = omit.From(val)
	}
}

// insertOptRels creates and inserts any optional the relationships on *models.Project
// according to the relationships in the template.
// any required relationship should have already exist on the model
func (o *ProjectTemplate) insertOptRels(ctx context.Context, exec bob.Executor, m *models.Project) error {
	var err error

	isTasksDone, _ := projectRelTasksCtx.Value(ctx)
	if !isTasksDone && o.r.Tasks != nil {
		ctx = projectRelTasksCtx.WithValue(ctx, true)
		for _, r := range o.r.Tasks {
			if r.o.alreadyPersisted {
				m.R.Tasks = append(m.R.Tasks, r.o.Build())
			} else {
				rel1, err := r.o.CreateMany(ctx, exec, r.number)
				if err != nil {
					return err
				}

				err = m.AttachTasks(ctx, exec, rel1...)
				if err != nil {
					return err
				}
			}
		}
	}

	return err
}

// Create builds a project and inserts it into the database
// Relations objects are also inserted and placed in the .R field
func (o *ProjectTemplate) Create(ctx context.Context, exec bob.Executor) (*models.Project, error) {
	var err error
	opt := o.BuildSetter()
	ensureCreatableProject(opt)

	if o.r.Workspace == nil {
		ProjectMods.WithNewWorkspace().Apply(ctx, o)
	}

	var rel0 *models.Workspace

	if o.r.Workspace.o.alreadyPersisted {
		rel0 = o.r.Workspace.o.Build()
	} else {
		rel0, err = o.r.Workspace.o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	opt.WorkspaceID = omit.From(rel0.ID)

	m, err := models.Projects.Insert(opt).One(ctx, exec)
	if err != nil {
		return nil, err
	}

	m.R.Workspace = rel0

	if err := o.insertOptRels(ctx, exec, m); err != nil {
		return nil, err
	}
	return m, err
}

// MustCreate builds a project and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o *ProjectTemplate) MustCreate(ctx context.Context, exec bob.Executor) *models.Project {
	m, err := o.Create(ctx, exec)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateOrFail builds a project and inserts it into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o *ProjectTemplate) CreateOrFail(ctx context.Context, tb testing.TB, exec bob.Executor) *models.Project {
	tb.Helper()
	m, err := o.Create(ctx, exec)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// CreateMany builds multiple projects and inserts them into the database
// Relations objects are also inserted and placed in the .R field
func (o ProjectTemplate) CreateMany(ctx context.Context, exec bob.Executor, number int) (models.ProjectSlice, error) {
	var err error
	m := make(models.ProjectSlice, number)

	for i := range m {
		m[i], err = o.Create(ctx, exec)
		if err != nil {
			return nil, err
		}
	}

	return m, nil
}

// MustCreateMany builds multiple projects and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// panics if an error occurs
func (o ProjectTemplate) MustCreateMany(ctx context.Context, exec bob.Executor, number int) models.ProjectSlice {
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		panic(err)
	}
	return m
}

// CreateManyOrFail builds multiple projects and inserts them into the database
// Relations objects are also inserted and placed in the .R field
// It calls `tb.Fatal(err)` on the test/benchmark if an error occurs
func (o ProjectTemplate) CreateManyOrFail(ctx context.Context, tb testing.TB, exec bob.Executor, number int) models.ProjectSlice {
	tb.Helper()
	m, err := o.CreateMany(ctx, exec, number)
	if err != nil {
		tb.Fatal(err)
		return nil
	}
	return m
}

// Project has methods that act as mods for the ProjectTemplate
var ProjectMods projectMods

type projectMods struct{}

func (m projectMods) RandomizeAllColumns(f *faker.Faker) ProjectMod {
	return ProjectModSlice{
		ProjectMods.RandomID(f),
		ProjectMods.RandomWorkspaceID(f),
		ProjectMods.RandomName(f),
		ProjectMods.RandomDescription(f),
		ProjectMods.RandomStatus(f),
	}
}

// Set the model columns to this value
func (m projectMods) ID(val uuid.UUID) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.ID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m projectMods) IDFunc(f func() uuid.UUID) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.ID = f
	})
}

// Clear any values for the column
func (m projectMods) UnsetID() ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.ID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m projectMods) RandomID(f *faker.Faker) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.ID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m projectMods) WorkspaceID(val uuid.UUID) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.WorkspaceID = func() uuid.UUID { return val }
	})
}

// Set the Column from the function
func (m projectMods) WorkspaceIDFunc(f func() uuid.UUID) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.WorkspaceID = f
	})
}

// Clear any values for the column
func (m projectMods) UnsetWorkspaceID() ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.WorkspaceID = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m projectMods) RandomWorkspaceID(f *faker.Faker) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.WorkspaceID = func() uuid.UUID {
			return random_uuid_UUID(f)
		}
	})
}

// Set the model columns to this value
func (m projectMods) Name(val string) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Name = func() string { return val }
	})
}

// Set the Column from the function
func (m projectMods) NameFunc(f func() string) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Name = f
	})
}

// Clear any values for the column
func (m projectMods) UnsetName() ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Name = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m projectMods) RandomName(f *faker.Faker) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Name = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m projectMods) Description(val string) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Description = func() string { return val }
	})
}

// Set the Column from the function
func (m projectMods) DescriptionFunc(f func() string) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Description = f
	})
}

// Clear any values for the column
func (m projectMods) UnsetDescription() ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Description = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m projectMods) RandomDescription(f *faker.Faker) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Description = func() string {
			return random_string(f)
		}
	})
}

// Set the model columns to this value
func (m projectMods) Status(val enums.ProjectStatus) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Status = func() enums.ProjectStatus { return val }
	})
}

// Set the Column from the function
func (m projectMods) StatusFunc(f func() enums.ProjectStatus) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Status = f
	})
}

// Clear any values for the column
func (m projectMods) UnsetStatus() ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Status = nil
	})
}

// Generates a random value for the column using the given faker
// if faker is nil, a default faker is used
func (m projectMods) RandomStatus(f *faker.Faker) ProjectMod {
	return ProjectModFunc(func(_ context.Context, o *ProjectTemplate) {
		o.Status = func() enums.ProjectStatus {
			return random_enums_ProjectStatus(f)
		}
	})
}

func (m projectMods) WithParentsCascading() ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		if isDone, _ := projectWithParentsCascadingCtx.Value(ctx); isDone {
			return
		}
		ctx = projectWithParentsCascadingCtx.WithValue(ctx, true)
		{

			related := o.f.NewWorkspaceWithContext(ctx, WorkspaceMods.WithParentsCascading())
			m.WithWorkspace(related).Apply(ctx, o)
		}
	})
}

func (m projectMods) WithWorkspace(rel *WorkspaceTemplate) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		o.r.Workspace = &projectRWorkspaceR{
			o: rel,
		}
	})
}

func (m projectMods) WithNewWorkspace(mods ...WorkspaceMod) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		related := o.f.NewWorkspaceWithContext(ctx, mods...)

		m.WithWorkspace(related).Apply(ctx, o)
	})
}

func (m projectMods) WithExistingWorkspace(em *models.Workspace) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		o.r.Workspace = &projectRWorkspaceR{
			o: o.f.FromExistingWorkspace(em),
		}
	})
}

func (m projectMods) WithoutWorkspace() ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		o.r.Workspace = nil
	})
}

func (m projectMods) WithTasks(number int, related *TaskTemplate) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		o.r.Tasks = []*projectRTasksR{{
			number: number,
			o:      related,
		}}
	})
}

func (m projectMods) WithNewTasks(number int, mods ...TaskMod) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		related := o.f.NewTaskWithContext(ctx, mods...)
		m.WithTasks(number, related).Apply(ctx, o)
	})
}

func (m projectMods) AddTasks(number int, related *TaskTemplate) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		o.r.Tasks = append(o.r.Tasks, &projectRTasksR{
			number: number,
			o:      related,
		})
	})
}

func (m projectMods) AddNewTasks(number int, mods ...TaskMod) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		related := o.f.NewTaskWithContext(ctx, mods...)
		m.AddTasks(number, related).Apply(ctx, o)
	})
}

func (m projectMods) AddExistingTasks(existingModels ...*models.Task) ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		for _, em := range existingModels {
			o.r.Tasks = append(o.r.Tasks, &projectRTasksR{
				o: o.f.FromExistingTask(em),
			})
		}
	})
}

func (m projectMods) WithoutTasks() ProjectMod {
	return ProjectModFunc(func(ctx context.Context, o *ProjectTemplate) {
		o.r.Tasks = nil
	})
}
