// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateMember implements createMember operation.
//
// Add a member to a workspace.
//
// POST /workspaces/{wsId}/members
func (UnimplementedHandler) CreateMember(ctx context.Context, req *CreateMemberRequest, params CreateMemberParams) (r *Member, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateProject implements createProject operation.
//
// Create a project.
//
// POST /workspaces/{wsId}/projects
func (UnimplementedHandler) CreateProject(ctx context.Context, req *CreateProjectRequest, params CreateProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTask implements createTask operation.
//
// Create a task.
//
// POST /workspaces/{wsId}/tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskRequest, params CreateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTaskComment implements createTaskComment operation.
//
// Add a comment to a task.
//
// POST /workspaces/{wsId}/tasks/{taskId}/comments
func (UnimplementedHandler) CreateTaskComment(ctx context.Context, req *CreateTaskCommentRequest, params CreateTaskCommentParams) (r *TaskComment, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateWorkspace implements createWorkspace operation.
//
// Create a workspace.
//
// POST /workspaces
func (UnimplementedHandler) CreateWorkspace(ctx context.Context, req *CreateWorkspaceRequest) (r *Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMember implements deleteMember operation.
//
// Delete a member.
//
// DELETE /workspaces/{wsId}/members/{id}
func (UnimplementedHandler) DeleteMember(ctx context.Context, params DeleteMemberParams) error {
	return ht.ErrNotImplemented
}

// DeleteProject implements deleteProject operation.
//
// Delete a project.
//
// DELETE /workspaces/{wsId}/projects/{id}
func (UnimplementedHandler) DeleteProject(ctx context.Context, params DeleteProjectParams) error {
	return ht.ErrNotImplemented
}

// DeleteTask implements deleteTask operation.
//
// Delete a task.
//
// DELETE /workspaces/{wsId}/tasks/{id}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) error {
	return ht.ErrNotImplemented
}

// DeleteTaskComment implements deleteTaskComment operation.
//
// Delete a comment.
//
// DELETE /workspaces/{wsId}/tasks/{taskId}/comments/{id}
func (UnimplementedHandler) DeleteTaskComment(ctx context.Context, params DeleteTaskCommentParams) error {
	return ht.ErrNotImplemented
}

// DeleteWorkspace implements deleteWorkspace operation.
//
// Delete a workspace.
//
// DELETE /workspaces/{wsId}
func (UnimplementedHandler) DeleteWorkspace(ctx context.Context, params DeleteWorkspaceParams) error {
	return ht.ErrNotImplemented
}

// GetDashboard implements getDashboard operation.
//
// Get workspace dashboard overview.
//
// GET /workspaces/{wsId}/reports/dashboard
func (UnimplementedHandler) GetDashboard(ctx context.Context, params GetDashboardParams) (r *DashboardData, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMember implements getMember operation.
//
// Get a member by ID.
//
// GET /workspaces/{wsId}/members/{id}
func (UnimplementedHandler) GetMember(ctx context.Context, params GetMemberParams) (r *Member, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMemberSummary implements getMemberSummary operation.
//
// Get task summary per member.
//
// GET /workspaces/{wsId}/reports/member-summary
func (UnimplementedHandler) GetMemberSummary(ctx context.Context, params GetMemberSummaryParams) (r []MemberTaskSummary, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProject implements getProject operation.
//
// Get a project by ID.
//
// GET /workspaces/{wsId}/projects/{id}
func (UnimplementedHandler) GetProject(ctx context.Context, params GetProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// GetProjectStats implements getProjectStats operation.
//
// Get task statistics per project.
//
// GET /workspaces/{wsId}/reports/project-stats
func (UnimplementedHandler) GetProjectStats(ctx context.Context, params GetProjectStatsParams) (r []ProjectTaskStats, _ error) {
	return r, ht.ErrNotImplemented
}

// GetTask implements getTask operation.
//
// Get a task by ID with full relations (project, assignee, comments).
//
// GET /workspaces/{wsId}/tasks/{id}
func (UnimplementedHandler) GetTask(ctx context.Context, params GetTaskParams) (r *TaskDetail, _ error) {
	return r, ht.ErrNotImplemented
}

// GetWorkspace implements getWorkspace operation.
//
// Get a workspace by ID.
//
// GET /workspaces/{wsId}
func (UnimplementedHandler) GetWorkspace(ctx context.Context, params GetWorkspaceParams) (r *Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMembers implements listMembers operation.
//
// List members in a workspace.
//
// GET /workspaces/{wsId}/members
func (UnimplementedHandler) ListMembers(ctx context.Context, params ListMembersParams) (r []Member, _ error) {
	return r, ht.ErrNotImplemented
}

// ListProjects implements listProjects operation.
//
// List projects in a workspace.
//
// GET /workspaces/{wsId}/projects
func (UnimplementedHandler) ListProjects(ctx context.Context, params ListProjectsParams) (r []ProjectWithStats, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTaskComments implements listTaskComments operation.
//
// List comments on a task.
//
// GET /workspaces/{wsId}/tasks/{taskId}/comments
func (UnimplementedHandler) ListTaskComments(ctx context.Context, params ListTaskCommentsParams) (r []TaskComment, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements listTasks operation.
//
// List tasks with optional filters.
//
// GET /workspaces/{wsId}/tasks
func (UnimplementedHandler) ListTasks(ctx context.Context, params ListTasksParams) (r []TaskWithRelations, _ error) {
	return r, ht.ErrNotImplemented
}

// ListWorkspaces implements listWorkspaces operation.
//
// List all workspaces.
//
// GET /workspaces
func (UnimplementedHandler) ListWorkspaces(ctx context.Context) (r []Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMember implements updateMember operation.
//
// Update a member.
//
// PUT /workspaces/{wsId}/members/{id}
func (UnimplementedHandler) UpdateMember(ctx context.Context, req *UpdateMemberRequest, params UpdateMemberParams) (r *Member, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateProject implements updateProject operation.
//
// Update a project.
//
// PUT /workspaces/{wsId}/projects/{id}
func (UnimplementedHandler) UpdateProject(ctx context.Context, req *UpdateProjectRequest, params UpdateProjectParams) (r *Project, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTask implements updateTask operation.
//
// Update a task.
//
// PUT /workspaces/{wsId}/tasks/{id}
func (UnimplementedHandler) UpdateTask(ctx context.Context, req *UpdateTaskRequest, params UpdateTaskParams) (r *Task, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTaskComment implements updateTaskComment operation.
//
// Update a comment.
//
// PUT /workspaces/{wsId}/tasks/{taskId}/comments/{id}
func (UnimplementedHandler) UpdateTaskComment(ctx context.Context, req *UpdateTaskCommentRequest, params UpdateTaskCommentParams) (r *TaskComment, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateWorkspace implements updateWorkspace operation.
//
// Update a workspace.
//
// PUT /workspaces/{wsId}
func (UnimplementedHandler) UpdateWorkspace(ctx context.Context, req *UpdateWorkspaceRequest, params UpdateWorkspaceParams) (r *Workspace, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResponseStatusCode) {
	r = new(ErrorResponseStatusCode)
	return r
}
