// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"time"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

func (s *ErrorResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/CreateMemberRequest
type CreateMemberRequest struct {
	Name  string     `json:"name"`
	Email string     `json:"email"`
	Role  MemberRole `json:"role"`
}

// GetName returns the value of Name.
func (s *CreateMemberRequest) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *CreateMemberRequest) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *CreateMemberRequest) GetRole() MemberRole {
	return s.Role
}

// SetName sets the value of Name.
func (s *CreateMemberRequest) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *CreateMemberRequest) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *CreateMemberRequest) SetRole(val MemberRole) {
	s.Role = val
}

// Ref: #/components/schemas/CreateProjectRequest
type CreateProjectRequest struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
}

// GetName returns the value of Name.
func (s *CreateProjectRequest) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *CreateProjectRequest) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *CreateProjectRequest) GetStatus() ProjectStatus {
	return s.Status
}

// SetName sets the value of Name.
func (s *CreateProjectRequest) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *CreateProjectRequest) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *CreateProjectRequest) SetStatus(val ProjectStatus) {
	s.Status = val
}

// Ref: #/components/schemas/CreateTaskCommentRequest
type CreateTaskCommentRequest struct {
	AuthorID uuid.UUID `json:"author_id"`
	Body     string    `json:"body"`
}

// GetAuthorID returns the value of AuthorID.
func (s *CreateTaskCommentRequest) GetAuthorID() uuid.UUID {
	return s.AuthorID
}

// GetBody returns the value of Body.
func (s *CreateTaskCommentRequest) GetBody() string {
	return s.Body
}

// SetAuthorID sets the value of AuthorID.
func (s *CreateTaskCommentRequest) SetAuthorID(val uuid.UUID) {
	s.AuthorID = val
}

// SetBody sets the value of Body.
func (s *CreateTaskCommentRequest) SetBody(val string) {
	s.Body = val
}

// Ref: #/components/schemas/CreateTaskRequest
type CreateTaskRequest struct {
	ProjectID   uuid.UUID    `json:"project_id"`
	AssigneeID  OptUUID      `json:"assignee_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      TaskStatus   `json:"status"`
	Priority    TaskPriority `json:"priority"`
	DueDate     OptDate      `json:"due_date"`
}

// GetProjectID returns the value of ProjectID.
func (s *CreateTaskRequest) GetProjectID() uuid.UUID {
	return s.ProjectID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *CreateTaskRequest) GetAssigneeID() OptUUID {
	return s.AssigneeID
}

// GetTitle returns the value of Title.
func (s *CreateTaskRequest) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *CreateTaskRequest) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *CreateTaskRequest) GetStatus() TaskStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *CreateTaskRequest) GetPriority() TaskPriority {
	return s.Priority
}

// GetDueDate returns the value of DueDate.
func (s *CreateTaskRequest) GetDueDate() OptDate {
	return s.DueDate
}

// SetProjectID sets the value of ProjectID.
func (s *CreateTaskRequest) SetProjectID(val uuid.UUID) {
	s.ProjectID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *CreateTaskRequest) SetAssigneeID(val OptUUID) {
	s.AssigneeID = val
}

// SetTitle sets the value of Title.
func (s *CreateTaskRequest) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *CreateTaskRequest) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *CreateTaskRequest) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *CreateTaskRequest) SetPriority(val TaskPriority) {
	s.Priority = val
}

// SetDueDate sets the value of DueDate.
func (s *CreateTaskRequest) SetDueDate(val OptDate) {
	s.DueDate = val
}

// Ref: #/components/schemas/CreateWorkspaceRequest
type CreateWorkspaceRequest struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *CreateWorkspaceRequest) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *CreateWorkspaceRequest) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/DashboardData
type DashboardData struct {
	ProjectCount int64 `json:"project_count"`
	MemberCount  int64 `json:"member_count"`
	TotalTasks   int64 `json:"total_tasks"`
	DoneTasks    int64 `json:"done_tasks"`
	OverdueTasks int64 `json:"overdue_tasks"`
}

// GetProjectCount returns the value of ProjectCount.
func (s *DashboardData) GetProjectCount() int64 {
	return s.ProjectCount
}

// GetMemberCount returns the value of MemberCount.
func (s *DashboardData) GetMemberCount() int64 {
	return s.MemberCount
}

// GetTotalTasks returns the value of TotalTasks.
func (s *DashboardData) GetTotalTasks() int64 {
	return s.TotalTasks
}

// GetDoneTasks returns the value of DoneTasks.
func (s *DashboardData) GetDoneTasks() int64 {
	return s.DoneTasks
}

// GetOverdueTasks returns the value of OverdueTasks.
func (s *DashboardData) GetOverdueTasks() int64 {
	return s.OverdueTasks
}

// SetProjectCount sets the value of ProjectCount.
func (s *DashboardData) SetProjectCount(val int64) {
	s.ProjectCount = val
}

// SetMemberCount sets the value of MemberCount.
func (s *DashboardData) SetMemberCount(val int64) {
	s.MemberCount = val
}

// SetTotalTasks sets the value of TotalTasks.
func (s *DashboardData) SetTotalTasks(val int64) {
	s.TotalTasks = val
}

// SetDoneTasks sets the value of DoneTasks.
func (s *DashboardData) SetDoneTasks(val int64) {
	s.DoneTasks = val
}

// SetOverdueTasks sets the value of OverdueTasks.
func (s *DashboardData) SetOverdueTasks(val int64) {
	s.OverdueTasks = val
}

// DeleteMemberNoContent is response for DeleteMember operation.
type DeleteMemberNoContent struct{}

// DeleteProjectNoContent is response for DeleteProject operation.
type DeleteProjectNoContent struct{}

// DeleteTaskCommentNoContent is response for DeleteTaskComment operation.
type DeleteTaskCommentNoContent struct{}

// DeleteTaskNoContent is response for DeleteTask operation.
type DeleteTaskNoContent struct{}

// DeleteWorkspaceNoContent is response for DeleteWorkspace operation.
type DeleteWorkspaceNoContent struct{}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *ErrorResponse) GetCode() int {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *ErrorResponse) SetCode(val int) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

// ErrorResponseStatusCode wraps ErrorResponse with StatusCode.
type ErrorResponseStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorResponseStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorResponseStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/Member
type Member struct {
	ID          uuid.UUID  `json:"id"`
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Name        string     `json:"name"`
	Email       string     `json:"email"`
	Role        MemberRole `json:"role"`
}

// GetID returns the value of ID.
func (s *Member) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *Member) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetName returns the value of Name.
func (s *Member) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *Member) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *Member) GetRole() MemberRole {
	return s.Role
}

// SetID sets the value of ID.
func (s *Member) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *Member) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetName sets the value of Name.
func (s *Member) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *Member) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *Member) SetRole(val MemberRole) {
	s.Role = val
}

// Ref: #/components/schemas/MemberRole
type MemberRole string

const (
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleEditor MemberRole = "editor"
	MemberRoleViewer MemberRole = "viewer"
)

// AllValues returns all MemberRole values.
func (MemberRole) AllValues() []MemberRole {
	return []MemberRole{
		MemberRoleOwner,
		MemberRoleEditor,
		MemberRoleViewer,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s MemberRole) MarshalText() ([]byte, error) {
	switch s {
	case MemberRoleOwner:
		return []byte(s), nil
	case MemberRoleEditor:
		return []byte(s), nil
	case MemberRoleViewer:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *MemberRole) UnmarshalText(data []byte) error {
	switch MemberRole(data) {
	case MemberRoleOwner:
		*s = MemberRoleOwner
		return nil
	case MemberRoleEditor:
		*s = MemberRoleEditor
		return nil
	case MemberRoleViewer:
		*s = MemberRoleViewer
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/MemberTaskSummary
type MemberTaskSummary struct {
	ID             uuid.UUID `json:"id"`
	Name           string    `json:"name"`
	AssignedTasks  int64     `json:"assigned_tasks"`
	CompletedTasks int64     `json:"completed_tasks"`
	OverdueTasks   int64     `json:"overdue_tasks"`
}

// GetID returns the value of ID.
func (s *MemberTaskSummary) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *MemberTaskSummary) GetName() string {
	return s.Name
}

// GetAssignedTasks returns the value of AssignedTasks.
func (s *MemberTaskSummary) GetAssignedTasks() int64 {
	return s.AssignedTasks
}

// GetCompletedTasks returns the value of CompletedTasks.
func (s *MemberTaskSummary) GetCompletedTasks() int64 {
	return s.CompletedTasks
}

// GetOverdueTasks returns the value of OverdueTasks.
func (s *MemberTaskSummary) GetOverdueTasks() int64 {
	return s.OverdueTasks
}

// SetID sets the value of ID.
func (s *MemberTaskSummary) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *MemberTaskSummary) SetName(val string) {
	s.Name = val
}

// SetAssignedTasks sets the value of AssignedTasks.
func (s *MemberTaskSummary) SetAssignedTasks(val int64) {
	s.AssignedTasks = val
}

// SetCompletedTasks sets the value of CompletedTasks.
func (s *MemberTaskSummary) SetCompletedTasks(val int64) {
	s.CompletedTasks = val
}

// SetOverdueTasks sets the value of OverdueTasks.
func (s *MemberTaskSummary) SetOverdueTasks(val int64) {
	s.OverdueTasks = val
}

// NewOptDate returns new OptDate with value set to v.
func NewOptDate(v time.Time) OptDate {
	return OptDate{
		Value: v,
		Set:   true,
	}
}

// OptDate is optional time.Time.
type OptDate struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDate was set.
func (o OptDate) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDate) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDate) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDate) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDate) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptMember returns new OptMember with value set to v.
func NewOptMember(v Member) OptMember {
	return OptMember{
		Value: v,
		Set:   true,
	}
}

// OptMember is optional Member.
type OptMember struct {
	Value Member
	Set   bool
}

// IsSet returns true if OptMember was set.
func (o OptMember) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptMember) Reset() {
	var v Member
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptMember) SetTo(v Member) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptMember) Get() (v Member, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptMember) Or(d Member) Member {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskPriority returns new OptTaskPriority with value set to v.
func NewOptTaskPriority(v TaskPriority) OptTaskPriority {
	return OptTaskPriority{
		Value: v,
		Set:   true,
	}
}

// OptTaskPriority is optional TaskPriority.
type OptTaskPriority struct {
	Value TaskPriority
	Set   bool
}

// IsSet returns true if OptTaskPriority was set.
func (o OptTaskPriority) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskPriority) Reset() {
	var v TaskPriority
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskPriority) SetTo(v TaskPriority) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskPriority) Get() (v TaskPriority, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskPriority) Or(d TaskPriority) TaskPriority {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTaskStatus returns new OptTaskStatus with value set to v.
func NewOptTaskStatus(v TaskStatus) OptTaskStatus {
	return OptTaskStatus{
		Value: v,
		Set:   true,
	}
}

// OptTaskStatus is optional TaskStatus.
type OptTaskStatus struct {
	Value TaskStatus
	Set   bool
}

// IsSet returns true if OptTaskStatus was set.
func (o OptTaskStatus) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTaskStatus) Reset() {
	var v TaskStatus
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTaskStatus) SetTo(v TaskStatus) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTaskStatus) Get() (v TaskStatus, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTaskStatus) Or(d TaskStatus) TaskStatus {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Project
type Project struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
}

// GetID returns the value of ID.
func (s *Project) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *Project) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetName returns the value of Name.
func (s *Project) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *Project) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *Project) GetStatus() ProjectStatus {
	return s.Status
}

// SetID sets the value of ID.
func (s *Project) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *Project) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetName sets the value of Name.
func (s *Project) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *Project) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *Project) SetStatus(val ProjectStatus) {
	s.Status = val
}

// Ref: #/components/schemas/ProjectStatus
type ProjectStatus string

const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusArchived ProjectStatus = "archived"
)

// AllValues returns all ProjectStatus values.
func (ProjectStatus) AllValues() []ProjectStatus {
	return []ProjectStatus{
		ProjectStatusActive,
		ProjectStatusArchived,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProjectStatus) MarshalText() ([]byte, error) {
	switch s {
	case ProjectStatusActive:
		return []byte(s), nil
	case ProjectStatusArchived:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProjectStatus) UnmarshalText(data []byte) error {
	switch ProjectStatus(data) {
	case ProjectStatusActive:
		*s = ProjectStatusActive
		return nil
	case ProjectStatusArchived:
		*s = ProjectStatusArchived
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/ProjectTaskStats
type ProjectTaskStats struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	TotalTasks  int64     `json:"total_tasks"`
	DoneTasks   int64     `json:"done_tasks"`
	ActiveTasks int64     `json:"active_tasks"`
}

// GetID returns the value of ID.
func (s *ProjectTaskStats) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *ProjectTaskStats) GetName() string {
	return s.Name
}

// GetTotalTasks returns the value of TotalTasks.
func (s *ProjectTaskStats) GetTotalTasks() int64 {
	return s.TotalTasks
}

// GetDoneTasks returns the value of DoneTasks.
func (s *ProjectTaskStats) GetDoneTasks() int64 {
	return s.DoneTasks
}

// GetActiveTasks returns the value of ActiveTasks.
func (s *ProjectTaskStats) GetActiveTasks() int64 {
	return s.ActiveTasks
}

// SetID sets the value of ID.
func (s *ProjectTaskStats) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *ProjectTaskStats) SetName(val string) {
	s.Name = val
}

// SetTotalTasks sets the value of TotalTasks.
func (s *ProjectTaskStats) SetTotalTasks(val int64) {
	s.TotalTasks = val
}

// SetDoneTasks sets the value of DoneTasks.
func (s *ProjectTaskStats) SetDoneTasks(val int64) {
	s.DoneTasks = val
}

// SetActiveTasks sets the value of ActiveTasks.
func (s *ProjectTaskStats) SetActiveTasks(val int64) {
	s.ActiveTasks = val
}

// Ref: #/components/schemas/ProjectWithStats
type ProjectWithStats struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
	TotalTasks  int64         `json:"total_tasks"`
	DoneTasks   int64         `json:"done_tasks"`
	ActiveTasks int64         `json:"active_tasks"`
}

// GetID returns the value of ID.
func (s *ProjectWithStats) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *ProjectWithStats) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetName returns the value of Name.
func (s *ProjectWithStats) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *ProjectWithStats) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *ProjectWithStats) GetStatus() ProjectStatus {
	return s.Status
}

// GetTotalTasks returns the value of TotalTasks.
func (s *ProjectWithStats) GetTotalTasks() int64 {
	return s.TotalTasks
}

// GetDoneTasks returns the value of DoneTasks.
func (s *ProjectWithStats) GetDoneTasks() int64 {
	return s.DoneTasks
}

// GetActiveTasks returns the value of ActiveTasks.
func (s *ProjectWithStats) GetActiveTasks() int64 {
	return s.ActiveTasks
}

// SetID sets the value of ID.
func (s *ProjectWithStats) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *ProjectWithStats) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetName sets the value of Name.
func (s *ProjectWithStats) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *ProjectWithStats) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *ProjectWithStats) SetStatus(val ProjectStatus) {
	s.Status = val
}

// SetTotalTasks sets the value of TotalTasks.
func (s *ProjectWithStats) SetTotalTasks(val int64) {
	s.TotalTasks = val
}

// SetDoneTasks sets the value of DoneTasks.
func (s *ProjectWithStats) SetDoneTasks(val int64) {
	s.DoneTasks = val
}

// SetActiveTasks sets the value of ActiveTasks.
func (s *ProjectWithStats) SetActiveTasks(val int64) {
	s.ActiveTasks = val
}

// Ref: #/components/schemas/Task
type Task struct {
	ID          uuid.UUID    `json:"id"`
	WorkspaceID uuid.UUID    `json:"workspace_id"`
	ProjectID   uuid.UUID    `json:"project_id"`
	AssigneeID  OptUUID      `json:"assignee_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      TaskStatus   `json:"status"`
	Priority    TaskPriority `json:"priority"`
	DueDate     OptDate      `json:"due_date"`
}

// GetID returns the value of ID.
func (s *Task) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *Task) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetProjectID returns the value of ProjectID.
func (s *Task) GetProjectID() uuid.UUID {
	return s.ProjectID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *Task) GetAssigneeID() OptUUID {
	return s.AssigneeID
}

// GetTitle returns the value of Title.
func (s *Task) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Task) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *Task) GetStatus() TaskStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *Task) GetPriority() TaskPriority {
	return s.Priority
}

// GetDueDate returns the value of DueDate.
func (s *Task) GetDueDate() OptDate {
	return s.DueDate
}

// SetID sets the value of ID.
func (s *Task) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *Task) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetProjectID sets the value of ProjectID.
func (s *Task) SetProjectID(val uuid.UUID) {
	s.ProjectID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *Task) SetAssigneeID(val OptUUID) {
	s.AssigneeID = val
}

// SetTitle sets the value of Title.
func (s *Task) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Task) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *Task) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *Task) SetPriority(val TaskPriority) {
	s.Priority = val
}

// SetDueDate sets the value of DueDate.
func (s *Task) SetDueDate(val OptDate) {
	s.DueDate = val
}

// Ref: #/components/schemas/TaskComment
type TaskComment struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	TaskID      uuid.UUID `json:"task_id"`
	AuthorID    uuid.UUID `json:"author_id"`
	Body        string    `json:"body"`
}

// GetID returns the value of ID.
func (s *TaskComment) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *TaskComment) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetTaskID returns the value of TaskID.
func (s *TaskComment) GetTaskID() uuid.UUID {
	return s.TaskID
}

// GetAuthorID returns the value of AuthorID.
func (s *TaskComment) GetAuthorID() uuid.UUID {
	return s.AuthorID
}

// GetBody returns the value of Body.
func (s *TaskComment) GetBody() string {
	return s.Body
}

// SetID sets the value of ID.
func (s *TaskComment) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *TaskComment) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetTaskID sets the value of TaskID.
func (s *TaskComment) SetTaskID(val uuid.UUID) {
	s.TaskID = val
}

// SetAuthorID sets the value of AuthorID.
func (s *TaskComment) SetAuthorID(val uuid.UUID) {
	s.AuthorID = val
}

// SetBody sets the value of Body.
func (s *TaskComment) SetBody(val string) {
	s.Body = val
}

// Ref: #/components/schemas/TaskDetail
type TaskDetail struct {
	ID          uuid.UUID     `json:"id"`
	WorkspaceID uuid.UUID     `json:"workspace_id"`
	ProjectID   uuid.UUID     `json:"project_id"`
	AssigneeID  OptUUID       `json:"assignee_id"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status      TaskStatus    `json:"status"`
	Priority    TaskPriority  `json:"priority"`
	DueDate     OptDate       `json:"due_date"`
	Project     Project       `json:"project"`
	Assignee    OptMember     `json:"assignee"`
	Comments    []TaskComment `json:"comments"`
}

// GetID returns the value of ID.
func (s *TaskDetail) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *TaskDetail) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetProjectID returns the value of ProjectID.
func (s *TaskDetail) GetProjectID() uuid.UUID {
	return s.ProjectID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *TaskDetail) GetAssigneeID() OptUUID {
	return s.AssigneeID
}

// GetTitle returns the value of Title.
func (s *TaskDetail) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *TaskDetail) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *TaskDetail) GetStatus() TaskStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *TaskDetail) GetPriority() TaskPriority {
	return s.Priority
}

// GetDueDate returns the value of DueDate.
func (s *TaskDetail) GetDueDate() OptDate {
	return s.DueDate
}

// GetProject returns the value of Project.
func (s *TaskDetail) GetProject() Project {
	return s.Project
}

// GetAssignee returns the value of Assignee.
func (s *TaskDetail) GetAssignee() OptMember {
	return s.Assignee
}

// GetComments returns the value of Comments.
func (s *TaskDetail) GetComments() []TaskComment {
	return s.Comments
}

// SetID sets the value of ID.
func (s *TaskDetail) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *TaskDetail) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetProjectID sets the value of ProjectID.
func (s *TaskDetail) SetProjectID(val uuid.UUID) {
	s.ProjectID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *TaskDetail) SetAssigneeID(val OptUUID) {
	s.AssigneeID = val
}

// SetTitle sets the value of Title.
func (s *TaskDetail) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *TaskDetail) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *TaskDetail) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *TaskDetail) SetPriority(val TaskPriority) {
	s.Priority = val
}

// SetDueDate sets the value of DueDate.
func (s *TaskDetail) SetDueDate(val OptDate) {
	s.DueDate = val
}

// SetProject sets the value of Project.
func (s *TaskDetail) SetProject(val Project) {
	s.Project = val
}

// SetAssignee sets the value of Assignee.
func (s *TaskDetail) SetAssignee(val OptMember) {
	s.Assignee = val
}

// SetComments sets the value of Comments.
func (s *TaskDetail) SetComments(val []TaskComment) {
	s.Comments = val
}

// Ref: #/components/schemas/TaskPriority
type TaskPriority string

const (
	TaskPriorityLow    TaskPriority = "low"
	TaskPriorityMedium TaskPriority = "medium"
	TaskPriorityHigh   TaskPriority = "high"
	TaskPriorityUrgent TaskPriority = "urgent"
)

// AllValues returns all TaskPriority values.
func (TaskPriority) AllValues() []TaskPriority {
	return []TaskPriority{
		TaskPriorityLow,
		TaskPriorityMedium,
		TaskPriorityHigh,
		TaskPriorityUrgent,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskPriority) MarshalText() ([]byte, error) {
	switch s {
	case TaskPriorityLow:
		return []byte(s), nil
	case TaskPriorityMedium:
		return []byte(s), nil
	case TaskPriorityHigh:
		return []byte(s), nil
	case TaskPriorityUrgent:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TaskPriority) UnmarshalText(data []byte) error {
	switch TaskPriority(data) {
	case TaskPriorityLow:
		*s = TaskPriorityLow
		return nil
	case TaskPriorityMedium:
		*s = TaskPriorityMedium
		return nil
	case TaskPriorityHigh:
		*s = TaskPriorityHigh
		return nil
	case TaskPriorityUrgent:
		*s = TaskPriorityUrgent
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TaskStatus
type TaskStatus string

const (
	TaskStatusTodo       TaskStatus = "todo"
	TaskStatusInProgress TaskStatus = "in_progress"
	TaskStatusDone       TaskStatus = "done"
)

// AllValues returns all TaskStatus values.
func (TaskStatus) AllValues() []TaskStatus {
	return []TaskStatus{
		TaskStatusTodo,
		TaskStatusInProgress,
		TaskStatusDone,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s TaskStatus) MarshalText() ([]byte, error) {
	switch s {
	case TaskStatusTodo:
		return []byte(s), nil
	case TaskStatusInProgress:
		return []byte(s), nil
	case TaskStatusDone:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *TaskStatus) UnmarshalText(data []byte) error {
	switch TaskStatus(data) {
	case TaskStatusTodo:
		*s = TaskStatusTodo
		return nil
	case TaskStatusInProgress:
		*s = TaskStatusInProgress
		return nil
	case TaskStatusDone:
		*s = TaskStatusDone
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/TaskWithRelations
type TaskWithRelations struct {
	ID           uuid.UUID    `json:"id"`
	WorkspaceID  uuid.UUID    `json:"workspace_id"`
	ProjectID    uuid.UUID    `json:"project_id"`
	AssigneeID   OptUUID      `json:"assignee_id"`
	Title        string       `json:"title"`
	Description  string       `json:"description"`
	Status       TaskStatus   `json:"status"`
	Priority     TaskPriority `json:"priority"`
	DueDate      OptDate      `json:"due_date"`
	ProjectName  OptString    `json:"project_name"`
	AssigneeName OptString    `json:"assignee_name"`
}

// GetID returns the value of ID.
func (s *TaskWithRelations) GetID() uuid.UUID {
	return s.ID
}

// GetWorkspaceID returns the value of WorkspaceID.
func (s *TaskWithRelations) GetWorkspaceID() uuid.UUID {
	return s.WorkspaceID
}

// GetProjectID returns the value of ProjectID.
func (s *TaskWithRelations) GetProjectID() uuid.UUID {
	return s.ProjectID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *TaskWithRelations) GetAssigneeID() OptUUID {
	return s.AssigneeID
}

// GetTitle returns the value of Title.
func (s *TaskWithRelations) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *TaskWithRelations) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *TaskWithRelations) GetStatus() TaskStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *TaskWithRelations) GetPriority() TaskPriority {
	return s.Priority
}

// GetDueDate returns the value of DueDate.
func (s *TaskWithRelations) GetDueDate() OptDate {
	return s.DueDate
}

// GetProjectName returns the value of ProjectName.
func (s *TaskWithRelations) GetProjectName() OptString {
	return s.ProjectName
}

// GetAssigneeName returns the value of AssigneeName.
func (s *TaskWithRelations) GetAssigneeName() OptString {
	return s.AssigneeName
}

// SetID sets the value of ID.
func (s *TaskWithRelations) SetID(val uuid.UUID) {
	s.ID = val
}

// SetWorkspaceID sets the value of WorkspaceID.
func (s *TaskWithRelations) SetWorkspaceID(val uuid.UUID) {
	s.WorkspaceID = val
}

// SetProjectID sets the value of ProjectID.
func (s *TaskWithRelations) SetProjectID(val uuid.UUID) {
	s.ProjectID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *TaskWithRelations) SetAssigneeID(val OptUUID) {
	s.AssigneeID = val
}

// SetTitle sets the value of Title.
func (s *TaskWithRelations) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *TaskWithRelations) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *TaskWithRelations) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *TaskWithRelations) SetPriority(val TaskPriority) {
	s.Priority = val
}

// SetDueDate sets the value of DueDate.
func (s *TaskWithRelations) SetDueDate(val OptDate) {
	s.DueDate = val
}

// SetProjectName sets the value of ProjectName.
func (s *TaskWithRelations) SetProjectName(val OptString) {
	s.ProjectName = val
}

// SetAssigneeName sets the value of AssigneeName.
func (s *TaskWithRelations) SetAssigneeName(val OptString) {
	s.AssigneeName = val
}

// Ref: #/components/schemas/UpdateMemberRequest
type UpdateMemberRequest struct {
	Name  string     `json:"name"`
	Email string     `json:"email"`
	Role  MemberRole `json:"role"`
}

// GetName returns the value of Name.
func (s *UpdateMemberRequest) GetName() string {
	return s.Name
}

// GetEmail returns the value of Email.
func (s *UpdateMemberRequest) GetEmail() string {
	return s.Email
}

// GetRole returns the value of Role.
func (s *UpdateMemberRequest) GetRole() MemberRole {
	return s.Role
}

// SetName sets the value of Name.
func (s *UpdateMemberRequest) SetName(val string) {
	s.Name = val
}

// SetEmail sets the value of Email.
func (s *UpdateMemberRequest) SetEmail(val string) {
	s.Email = val
}

// SetRole sets the value of Role.
func (s *UpdateMemberRequest) SetRole(val MemberRole) {
	s.Role = val
}

// Ref: #/components/schemas/UpdateProjectRequest
type UpdateProjectRequest struct {
	Name        string        `json:"name"`
	Description string        `json:"description"`
	Status      ProjectStatus `json:"status"`
}

// GetName returns the value of Name.
func (s *UpdateProjectRequest) GetName() string {
	return s.Name
}

// GetDescription returns the value of Description.
func (s *UpdateProjectRequest) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *UpdateProjectRequest) GetStatus() ProjectStatus {
	return s.Status
}

// SetName sets the value of Name.
func (s *UpdateProjectRequest) SetName(val string) {
	s.Name = val
}

// SetDescription sets the value of Description.
func (s *UpdateProjectRequest) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *UpdateProjectRequest) SetStatus(val ProjectStatus) {
	s.Status = val
}

// Ref: #/components/schemas/UpdateTaskCommentRequest
type UpdateTaskCommentRequest struct {
	Body string `json:"body"`
}

// GetBody returns the value of Body.
func (s *UpdateTaskCommentRequest) GetBody() string {
	return s.Body
}

// SetBody sets the value of Body.
func (s *UpdateTaskCommentRequest) SetBody(val string) {
	s.Body = val
}

// Ref: #/components/schemas/UpdateTaskRequest
type UpdateTaskRequest struct {
	ProjectID   uuid.UUID    `json:"project_id"`
	AssigneeID  OptUUID      `json:"assignee_id"`
	Title       string       `json:"title"`
	Description string       `json:"description"`
	Status      TaskStatus   `json:"status"`
	Priority    TaskPriority `json:"priority"`
	DueDate     OptDate      `json:"due_date"`
}

// GetProjectID returns the value of ProjectID.
func (s *UpdateTaskRequest) GetProjectID() uuid.UUID {
	return s.ProjectID
}

// GetAssigneeID returns the value of AssigneeID.
func (s *UpdateTaskRequest) GetAssigneeID() OptUUID {
	return s.AssigneeID
}

// GetTitle returns the value of Title.
func (s *UpdateTaskRequest) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *UpdateTaskRequest) GetDescription() string {
	return s.Description
}

// GetStatus returns the value of Status.
func (s *UpdateTaskRequest) GetStatus() TaskStatus {
	return s.Status
}

// GetPriority returns the value of Priority.
func (s *UpdateTaskRequest) GetPriority() TaskPriority {
	return s.Priority
}

// GetDueDate returns the value of DueDate.
func (s *UpdateTaskRequest) GetDueDate() OptDate {
	return s.DueDate
}

// SetProjectID sets the value of ProjectID.
func (s *UpdateTaskRequest) SetProjectID(val uuid.UUID) {
	s.ProjectID = val
}

// SetAssigneeID sets the value of AssigneeID.
func (s *UpdateTaskRequest) SetAssigneeID(val OptUUID) {
	s.AssigneeID = val
}

// SetTitle sets the value of Title.
func (s *UpdateTaskRequest) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *UpdateTaskRequest) SetDescription(val string) {
	s.Description = val
}

// SetStatus sets the value of Status.
func (s *UpdateTaskRequest) SetStatus(val TaskStatus) {
	s.Status = val
}

// SetPriority sets the value of Priority.
func (s *UpdateTaskRequest) SetPriority(val TaskPriority) {
	s.Priority = val
}

// SetDueDate sets the value of DueDate.
func (s *UpdateTaskRequest) SetDueDate(val OptDate) {
	s.DueDate = val
}

// Ref: #/components/schemas/UpdateWorkspaceRequest
type UpdateWorkspaceRequest struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *UpdateWorkspaceRequest) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *UpdateWorkspaceRequest) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/Workspace
type Workspace struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// GetID returns the value of ID.
func (s *Workspace) GetID() uuid.UUID {
	return s.ID
}

// GetName returns the value of Name.
func (s *Workspace) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Workspace) SetID(val uuid.UUID) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Workspace) SetName(val string) {
	s.Name = val
}
