// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"github.com/stephenafamo/bob/clause"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
)

var (
	SelectWhere     = Where[*dialect.SelectQuery]()
	UpdateWhere     = Where[*dialect.UpdateQuery]()
	DeleteWhere     = Where[*dialect.DeleteQuery]()
	OnConflictWhere = Where[*clause.ConflictClause]() // Used in ON CONFLICT DO UPDATE
)

func Where[Q psql.Filterable]() struct {
	Members      memberWhere[Q]
	Projects     projectWhere[Q]
	TaskComments taskCommentWhere[Q]
	Tasks        taskWhere[Q]
	Workspaces   workspaceWhere[Q]
} {
	return struct {
		Members      memberWhere[Q]
		Projects     projectWhere[Q]
		TaskComments taskCommentWhere[Q]
		Tasks        taskWhere[Q]
		Workspaces   workspaceWhere[Q]
	}{
		Members:      buildMemberWhere[Q](Members.Columns),
		Projects:     buildProjectWhere[Q](Projects.Columns),
		TaskComments: buildTaskCommentWhere[Q](TaskComments.Columns),
		Tasks:        buildTaskWhere[Q](Tasks.Columns),
		Workspaces:   buildWorkspaceWhere[Q](Workspaces.Columns),
	}
}
