// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	enums "github.com/tak848/lxgo4-bob/internal/infra/dbgen/dbenums"
)

// Member is an object representing the database table.
type Member struct {
	ID          uuid.UUID        `db:"id,pk" json:"id"`
	WorkspaceID uuid.UUID        `db:"workspace_id" json:"workspace_id"`
	Name        string           `db:"name" json:"name"`
	Email       string           `db:"email" json:"email"`
	Role        enums.MemberRole `db:"role" json:"role"`

	R memberR `db:"-" json:"-"`

	C memberC `db:"-" json:"-"`
}

// MemberSlice is an alias for a slice of pointers to Member.
// This should almost always be used instead of []*Member.
type MemberSlice []*Member

// Members contains methods to work with the members table
var Members = psql.NewTablex[*Member, MemberSlice, *MemberSetter]("", "members", buildMemberColumns("members"))

// MembersQuery is a query on the members table
type MembersQuery = *psql.ViewQuery[*Member, MemberSlice]

// memberR is where relationships are stored.
type memberR struct {
	Workspace    *Workspace       `json:"Workspace"`    // members.members_workspace_id_fkey
	TaskComments TaskCommentSlice `json:"TaskComments"` // task_comments.task_comments_workspace_id_author_id_fkey
	Tasks        TaskSlice        `json:"Tasks"`        // tasks.tasks_workspace_id_assignee_id_fkey
}

func buildMemberColumns(tableName string) memberColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "workspace_id", "name", "email", "role",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return memberColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		WorkspaceID: psql.Quote(tableName, "workspace_id"),
		Name:        psql.Quote(tableName, "name"),
		Email:       psql.Quote(tableName, "email"),
		Role:        psql.Quote(tableName, "role"),
	}
}

type memberColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	WorkspaceID psql.Expression
	Name        psql.Expression
	Email       psql.Expression
	Role        psql.Expression
}

func (c memberColumns) Alias() string {
	return c.tableAlias
}

func (memberColumns) AliasedAs(tableName string) memberColumns {
	return buildMemberColumns(tableName)
}

func (c memberColumns) Unqualified() memberColumns {
	return buildMemberColumns("")
}

// MemberSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type MemberSetter struct {
	ID          omit.Val[uuid.UUID]        `db:"id,pk" json:"id"`
	WorkspaceID omit.Val[uuid.UUID]        `db:"workspace_id" json:"workspace_id"`
	Name        omit.Val[string]           `db:"name" json:"name"`
	Email       omit.Val[string]           `db:"email" json:"email"`
	Role        omit.Val[enums.MemberRole] `db:"role" json:"role"`
}

func (s MemberSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.WorkspaceID.IsValue() {
		vals = append(vals, "workspace_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Email.IsValue() {
		vals = append(vals, "email")
	}
	if s.Role.IsValue() {
		vals = append(vals, "role")
	}
	return vals
}

func (s MemberSetter) Overwrite(t *Member) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.WorkspaceID.IsValue() {
		t.WorkspaceID = s.WorkspaceID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Email.IsValue() {
		t.Email = s.Email.MustGet()
	}
	if s.Role.IsValue() {
		t.Role = s.Role.MustGet()
	}
}

func (s *MemberSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Members.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.WorkspaceID.IsValue() {
			vals[1] = psql.Arg(s.WorkspaceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Email.IsValue() {
			vals[3] = psql.Arg(s.Email.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Role.IsValue() {
			vals[4] = psql.Arg(s.Role.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s MemberSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s MemberSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.WorkspaceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workspace_id")...),
			psql.Arg(s.WorkspaceID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Email.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "email")...),
			psql.Arg(s.Email),
		}})
	}

	if s.Role.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "role")...),
			psql.Arg(s.Role),
		}})
	}

	return exprs
}

// FindMember retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindMember(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Member, error) {
	if len(cols) == 0 {
		return Members.Query(
			sm.Where(Members.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Members.Query(
		sm.Where(Members.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Members.Columns.Only(cols...)),
	).One(ctx, exec)
}

// MemberExists checks the presence of a single record by primary key
func MemberExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Members.Query(
		sm.Where(Members.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Member is retrieved from the database
func (o *Member) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Members.AfterSelectHooks.RunHooks(ctx, exec, MemberSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Members.AfterInsertHooks.RunHooks(ctx, exec, MemberSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Members.AfterUpdateHooks.RunHooks(ctx, exec, MemberSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Members.AfterDeleteHooks.RunHooks(ctx, exec, MemberSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Member
func (o *Member) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Member) pkEQ() dialect.Expression {
	return psql.Quote("members", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Member
func (o *Member) Update(ctx context.Context, exec bob.Executor, s *MemberSetter) error {
	v, err := Members.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Member record with an executor
func (o *Member) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Members.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Member using the executor
func (o *Member) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Members.Query(
		sm.Where(Members.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after MemberSlice is retrieved from the database
func (o MemberSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Members.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Members.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Members.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Members.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o MemberSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("members", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o MemberSlice) copyMatchingRows(from ...*Member) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o MemberSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Members.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Member:
				o.copyMatchingRows(retrieved)
			case []*Member:
				o.copyMatchingRows(retrieved...)
			case MemberSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Member or a slice of Member
				// then run the AfterUpdateHooks on the slice
				_, err = Members.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o MemberSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Members.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Member:
				o.copyMatchingRows(retrieved)
			case []*Member:
				o.copyMatchingRows(retrieved...)
			case MemberSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Member or a slice of Member
				// then run the AfterDeleteHooks on the slice
				_, err = Members.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o MemberSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals MemberSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Members.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o MemberSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Members.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o MemberSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Members.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Workspace starts a query for related objects on workspaces
func (o *Member) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	return Workspaces.Query(append(mods,
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.WorkspaceID))),
	)...)
}

func (os MemberSlice) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
	))

	return Workspaces.Query(append(mods,
		sm.Where(psql.Group(Workspaces.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// TaskComments starts a query for related objects on task_comments
func (o *Member) TaskComments(mods ...bob.Mod[*dialect.SelectQuery]) TaskCommentsQuery {
	return TaskComments.Query(append(mods,
		sm.Where(TaskComments.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(TaskComments.Columns.AuthorID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os MemberSlice) TaskComments(mods ...bob.Mod[*dialect.SelectQuery]) TaskCommentsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return TaskComments.Query(append(mods,
		sm.Where(psql.Group(TaskComments.Columns.WorkspaceID, TaskComments.Columns.AuthorID).OP("IN", PKArgExpr)),
	)...)
}

// Tasks starts a query for related objects on tasks
func (o *Member) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	return Tasks.Query(append(mods,
		sm.Where(Tasks.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Tasks.Columns.AssigneeID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os MemberSlice) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Tasks.Query(append(mods,
		sm.Where(psql.Group(Tasks.Columns.WorkspaceID, Tasks.Columns.AssigneeID).OP("IN", PKArgExpr)),
	)...)
}

func attachMemberWorkspace0(ctx context.Context, exec bob.Executor, count int, member0 *Member, workspace1 *Workspace) (*Member, error) {
	setter := &MemberSetter{
		WorkspaceID: omit.From(workspace1.ID),
	}

	err := member0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachMemberWorkspace0: %w", err)
	}

	return member0, nil
}

func (member0 *Member) InsertWorkspace(ctx context.Context, exec bob.Executor, related *WorkspaceSetter) error {
	var err error

	workspace1, err := Workspaces.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachMemberWorkspace0(ctx, exec, 1, member0, workspace1)
	if err != nil {
		return err
	}

	member0.R.Workspace = workspace1

	workspace1.R.Members = append(workspace1.R.Members, member0)

	return nil
}

func (member0 *Member) AttachWorkspace(ctx context.Context, exec bob.Executor, workspace1 *Workspace) error {
	var err error

	_, err = attachMemberWorkspace0(ctx, exec, 1, member0, workspace1)
	if err != nil {
		return err
	}

	member0.R.Workspace = workspace1

	workspace1.R.Members = append(workspace1.R.Members, member0)

	return nil
}

func insertMemberTaskComments0(ctx context.Context, exec bob.Executor, taskComments1 []*TaskCommentSetter, member0 *Member) (TaskCommentSlice, error) {
	for i := range taskComments1 {
		taskComments1[i].WorkspaceID = omit.From(member0.WorkspaceID)
		taskComments1[i].AuthorID = omit.From(member0.ID)
	}

	ret, err := TaskComments.Insert(bob.ToMods(taskComments1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertMemberTaskComments0: %w", err)
	}

	return ret, nil
}

func attachMemberTaskComments0(ctx context.Context, exec bob.Executor, count int, taskComments1 TaskCommentSlice, member0 *Member) (TaskCommentSlice, error) {
	setter := &TaskCommentSetter{
		WorkspaceID: omit.From(member0.WorkspaceID),
		AuthorID:    omit.From(member0.ID),
	}

	err := taskComments1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachMemberTaskComments0: %w", err)
	}

	return taskComments1, nil
}

func (member0 *Member) InsertTaskComments(ctx context.Context, exec bob.Executor, related ...*TaskCommentSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	taskComments1, err := insertMemberTaskComments0(ctx, exec, related, member0)
	if err != nil {
		return err
	}

	member0.R.TaskComments = append(member0.R.TaskComments, taskComments1...)

	for _, rel := range taskComments1 {
		rel.R.Member = member0
	}
	return nil
}

func (member0 *Member) AttachTaskComments(ctx context.Context, exec bob.Executor, related ...*TaskComment) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	taskComments1 := TaskCommentSlice(related)

	_, err = attachMemberTaskComments0(ctx, exec, len(related), taskComments1, member0)
	if err != nil {
		return err
	}

	member0.R.TaskComments = append(member0.R.TaskComments, taskComments1...)

	for _, rel := range related {
		rel.R.Member = member0
	}

	return nil
}

func insertMemberTasks0(ctx context.Context, exec bob.Executor, tasks1 []*TaskSetter, member0 *Member) (TaskSlice, error) {
	for i := range tasks1 {
		tasks1[i].WorkspaceID = omit.From(member0.WorkspaceID)
		tasks1[i].AssigneeID = omitnull.From(member0.ID)
	}

	ret, err := Tasks.Insert(bob.ToMods(tasks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertMemberTasks0: %w", err)
	}

	return ret, nil
}

func attachMemberTasks0(ctx context.Context, exec bob.Executor, count int, tasks1 TaskSlice, member0 *Member) (TaskSlice, error) {
	setter := &TaskSetter{
		WorkspaceID: omit.From(member0.WorkspaceID),
		AssigneeID:  omitnull.From(member0.ID),
	}

	err := tasks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachMemberTasks0: %w", err)
	}

	return tasks1, nil
}

func (member0 *Member) InsertTasks(ctx context.Context, exec bob.Executor, related ...*TaskSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tasks1, err := insertMemberTasks0(ctx, exec, related, member0)
	if err != nil {
		return err
	}

	member0.R.Tasks = append(member0.R.Tasks, tasks1...)

	for _, rel := range tasks1 {
		rel.R.Member = member0
	}
	return nil
}

func (member0 *Member) AttachTasks(ctx context.Context, exec bob.Executor, related ...*Task) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tasks1 := TaskSlice(related)

	_, err = attachMemberTasks0(ctx, exec, len(related), tasks1, member0)
	if err != nil {
		return err
	}

	member0.R.Tasks = append(member0.R.Tasks, tasks1...)

	for _, rel := range related {
		rel.R.Member = member0
	}

	return nil
}

type memberWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	WorkspaceID psql.WhereMod[Q, uuid.UUID]
	Name        psql.WhereMod[Q, string]
	Email       psql.WhereMod[Q, string]
	Role        psql.WhereMod[Q, enums.MemberRole]
}

func (memberWhere[Q]) AliasedAs(alias string) memberWhere[Q] {
	return buildMemberWhere[Q](buildMemberColumns(alias))
}

func buildMemberWhere[Q psql.Filterable](cols memberColumns) memberWhere[Q] {
	return memberWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		WorkspaceID: psql.Where[Q, uuid.UUID](cols.WorkspaceID),
		Name:        psql.Where[Q, string](cols.Name),
		Email:       psql.Where[Q, string](cols.Email),
		Role:        psql.Where[Q, enums.MemberRole](cols.Role),
	}
}

func (o *Member) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Workspace":
		rel, ok := retrieved.(*Workspace)
		if !ok {
			return fmt.Errorf("member cannot load %T as %q", retrieved, name)
		}

		o.R.Workspace = rel

		if rel != nil {
			rel.R.Members = MemberSlice{o}
		}
		return nil
	case "TaskComments":
		rels, ok := retrieved.(TaskCommentSlice)
		if !ok {
			return fmt.Errorf("member cannot load %T as %q", retrieved, name)
		}

		o.R.TaskComments = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Member = o
			}
		}
		return nil
	case "Tasks":
		rels, ok := retrieved.(TaskSlice)
		if !ok {
			return fmt.Errorf("member cannot load %T as %q", retrieved, name)
		}

		o.R.Tasks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Member = o
			}
		}
		return nil
	default:
		return fmt.Errorf("member has no relationship %q", name)
	}
}

type memberPreloader struct {
	Workspace func(...psql.PreloadOption) psql.Preloader
}

func buildMemberPreloader() memberPreloader {
	return memberPreloader{
		Workspace: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Workspace, WorkspaceSlice](psql.PreloadRel{
				Name: "Workspace",
				Sides: []psql.PreloadSide{
					{
						From:        Members,
						To:          Workspaces,
						FromColumns: []string{"workspace_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Workspaces.Columns.Names(), opts...)
		},
	}
}

type memberThenLoader[Q orm.Loadable] struct {
	Workspace    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tasks        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildMemberThenLoader[Q orm.Loadable]() memberThenLoader[Q] {
	type WorkspaceLoadInterface interface {
		LoadWorkspace(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskCommentsLoadInterface interface {
		LoadTaskComments(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TasksLoadInterface interface {
		LoadTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return memberThenLoader[Q]{
		Workspace: thenLoadBuilder[Q](
			"Workspace",
			func(ctx context.Context, exec bob.Executor, retrieved WorkspaceLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadWorkspace(ctx, exec, mods...)
			},
		),
		TaskComments: thenLoadBuilder[Q](
			"TaskComments",
			func(ctx context.Context, exec bob.Executor, retrieved TaskCommentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTaskComments(ctx, exec, mods...)
			},
		),
		Tasks: thenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadWorkspace loads the member's Workspace into the .R struct
func (o *Member) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Workspace = nil

	related, err := o.Workspace(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Members = MemberSlice{o}

	o.R.Workspace = related
	return nil
}

// LoadWorkspace loads the member's Workspace into the .R struct
func (os MemberSlice) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	workspaces, err := os.Workspace(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range workspaces {

			if !(o.WorkspaceID == rel.ID) {
				continue
			}

			rel.R.Members = append(rel.R.Members, o)

			o.R.Workspace = rel
			break
		}
	}

	return nil
}

// LoadTaskComments loads the member's TaskComments into the .R struct
func (o *Member) LoadTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TaskComments = nil

	related, err := o.TaskComments(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Member = o
	}

	o.R.TaskComments = related
	return nil
}

// LoadTaskComments loads the member's TaskComments into the .R struct
func (os MemberSlice) LoadTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	taskComments, err := os.TaskComments(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TaskComments = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range taskComments {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !(o.ID == rel.AuthorID) {
				continue
			}

			rel.R.Member = o

			o.R.TaskComments = append(o.R.TaskComments, rel)
		}
	}

	return nil
}

// LoadTasks loads the member's Tasks into the .R struct
func (o *Member) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tasks = nil

	related, err := o.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Member = o
	}

	o.R.Tasks = related
	return nil
}

// LoadTasks loads the member's Tasks into the .R struct
func (os MemberSlice) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tasks, err := os.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Tasks = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tasks {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !rel.AssigneeID.IsValue() {
				continue
			}
			if !(rel.AssigneeID.IsValue() && o.ID == rel.AssigneeID.MustGet()) {
				continue
			}

			rel.R.Member = o

			o.R.Tasks = append(o.R.Tasks, rel)
		}
	}

	return nil
}

// memberC is where relationship counts are stored.
type memberC struct {
	TaskComments *int64 `json:"TaskComments"`
	Tasks        *int64 `json:"Tasks"`
}

// PreloadCount sets a count in the C struct by name
func (o *Member) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TaskComments":
		o.C.TaskComments = &count
	case "Tasks":
		o.C.Tasks = &count
	}
	return nil
}

type memberCountPreloader struct {
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Tasks        func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildMemberCountPreloader() memberCountPreloader {
	return memberCountPreloader{
		TaskComments: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Member]("TaskComments", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Members.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(TaskComments.Name()),
					sm.Where(psql.Quote(TaskComments.Alias(), "workspace_id").EQ(psql.Quote(parent, "workspace_id"))),
					sm.Where(psql.Quote(TaskComments.Alias(), "author_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Tasks: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Member]("Tasks", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Members.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Tasks.Name()),
					sm.Where(psql.Quote(Tasks.Alias(), "workspace_id").EQ(psql.Quote(parent, "workspace_id"))),
					sm.Where(psql.Quote(Tasks.Alias(), "assignee_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type memberCountThenLoader[Q orm.Loadable] struct {
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tasks        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildMemberCountThenLoader[Q orm.Loadable]() memberCountThenLoader[Q] {
	type TaskCommentsCountInterface interface {
		LoadCountTaskComments(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TasksCountInterface interface {
		LoadCountTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return memberCountThenLoader[Q]{
		TaskComments: countThenLoadBuilder[Q](
			"TaskComments",
			func(ctx context.Context, exec bob.Executor, retrieved TaskCommentsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTaskComments(ctx, exec, mods...)
			},
		),
		Tasks: countThenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountTaskComments loads the count of TaskComments into the C struct
func (o *Member) LoadCountTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TaskComments(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TaskComments = &count
	return nil
}

// LoadCountTaskComments loads the count of TaskComments for a slice
func (os MemberSlice) LoadCountTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountTaskComments(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

// LoadCountTasks loads the count of Tasks into the C struct
func (o *Member) LoadCountTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Tasks(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Tasks = &count
	return nil
}

// LoadCountTasks loads the count of Tasks for a slice
func (os MemberSlice) LoadCountTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountTasks(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

type memberJoins[Q dialect.Joinable] struct {
	typ          string
	Workspace    modAs[Q, workspaceColumns]
	TaskComments modAs[Q, taskCommentColumns]
	Tasks        modAs[Q, taskColumns]
}

func (j memberJoins[Q]) aliasedAs(alias string) memberJoins[Q] {
	return buildMemberJoins[Q](buildMemberColumns(alias), j.typ)
}

func buildMemberJoins[Q dialect.Joinable](cols memberColumns, typ string) memberJoins[Q] {
	return memberJoins[Q]{
		typ: typ,
		Workspace: modAs[Q, workspaceColumns]{
			c: Workspaces.Columns,
			f: func(to workspaceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Workspaces.Name().As(to.Alias())).On(
						to.ID.EQ(cols.WorkspaceID),
					))
				}

				return mods
			},
		},
		TaskComments: modAs[Q, taskCommentColumns]{
			c: TaskComments.Columns,
			f: func(to taskCommentColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TaskComments.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.AuthorID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Tasks: modAs[Q, taskColumns]{
			c: Tasks.Columns,
			f: func(to taskColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tasks.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.AssigneeID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
