// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	enums "github.com/tak848/lxgo4-bob/internal/infra/dbgen/dbenums"
)

// Project is an object representing the database table.
type Project struct {
	ID          uuid.UUID           `db:"id,pk" json:"id"`
	WorkspaceID uuid.UUID           `db:"workspace_id" json:"workspace_id"`
	Name        string              `db:"name" json:"name"`
	Description string              `db:"description" json:"description"`
	Status      enums.ProjectStatus `db:"status" json:"status"`

	R projectR `db:"-" json:"-"`

	C projectC `db:"-" json:"-"`
}

// ProjectSlice is an alias for a slice of pointers to Project.
// This should almost always be used instead of []*Project.
type ProjectSlice []*Project

// Projects contains methods to work with the projects table
var Projects = psql.NewTablex[*Project, ProjectSlice, *ProjectSetter]("", "projects", buildProjectColumns("projects"))

// ProjectsQuery is a query on the projects table
type ProjectsQuery = *psql.ViewQuery[*Project, ProjectSlice]

// projectR is where relationships are stored.
type projectR struct {
	Workspace *Workspace `json:"Workspace"` // projects.projects_workspace_id_fkey
	Tasks     TaskSlice  `json:"Tasks"`     // tasks.tasks_workspace_id_project_id_fkey
}

func buildProjectColumns(tableName string) projectColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "workspace_id", "name", "description", "status",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return projectColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		WorkspaceID: psql.Quote(tableName, "workspace_id"),
		Name:        psql.Quote(tableName, "name"),
		Description: psql.Quote(tableName, "description"),
		Status:      psql.Quote(tableName, "status"),
	}
}

type projectColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	WorkspaceID psql.Expression
	Name        psql.Expression
	Description psql.Expression
	Status      psql.Expression
}

func (c projectColumns) Alias() string {
	return c.tableAlias
}

func (projectColumns) AliasedAs(tableName string) projectColumns {
	return buildProjectColumns(tableName)
}

func (c projectColumns) Unqualified() projectColumns {
	return buildProjectColumns("")
}

// ProjectSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type ProjectSetter struct {
	ID          omit.Val[uuid.UUID]           `db:"id,pk" json:"id"`
	WorkspaceID omit.Val[uuid.UUID]           `db:"workspace_id" json:"workspace_id"`
	Name        omit.Val[string]              `db:"name" json:"name"`
	Description omit.Val[string]              `db:"description" json:"description"`
	Status      omit.Val[enums.ProjectStatus] `db:"status" json:"status"`
}

func (s ProjectSetter) SetColumns() []string {
	vals := make([]string, 0, 5)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.WorkspaceID.IsValue() {
		vals = append(vals, "workspace_id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	if s.Description.IsValue() {
		vals = append(vals, "description")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	return vals
}

func (s ProjectSetter) Overwrite(t *Project) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.WorkspaceID.IsValue() {
		t.WorkspaceID = s.WorkspaceID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
	if s.Description.IsValue() {
		t.Description = s.Description.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
}

func (s *ProjectSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Projects.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 5)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.WorkspaceID.IsValue() {
			vals[1] = psql.Arg(s.WorkspaceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[2] = psql.Arg(s.Name.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if s.Description.IsValue() {
			vals[3] = psql.Arg(s.Description.MustGet())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[4] = psql.Arg(s.Status.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s ProjectSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s ProjectSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 5)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.WorkspaceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workspace_id")...),
			psql.Arg(s.WorkspaceID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	if s.Description.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	return exprs
}

// FindProject retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindProject(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Project, error) {
	if len(cols) == 0 {
		return Projects.Query(
			sm.Where(Projects.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Projects.Query(
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Projects.Columns.Only(cols...)),
	).One(ctx, exec)
}

// ProjectExists checks the presence of a single record by primary key
func ProjectExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Projects.Query(
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Project is retrieved from the database
func (o *Project) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Projects.AfterSelectHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Projects.AfterInsertHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, ProjectSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, ProjectSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Project
func (o *Project) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Project) pkEQ() dialect.Expression {
	return psql.Quote("projects", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Project
func (o *Project) Update(ctx context.Context, exec bob.Executor, s *ProjectSetter) error {
	v, err := Projects.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Project record with an executor
func (o *Project) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Projects.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Project using the executor
func (o *Project) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Projects.Query(
		sm.Where(Projects.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after ProjectSlice is retrieved from the database
func (o ProjectSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Projects.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Projects.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o ProjectSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("projects", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o ProjectSlice) copyMatchingRows(from ...*Project) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o ProjectSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterUpdateHooks on the slice
				_, err = Projects.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o ProjectSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Projects.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Project:
				o.copyMatchingRows(retrieved)
			case []*Project:
				o.copyMatchingRows(retrieved...)
			case ProjectSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Project or a slice of Project
				// then run the AfterDeleteHooks on the slice
				_, err = Projects.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o ProjectSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals ProjectSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Projects.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o ProjectSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Projects.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o ProjectSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Projects.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Workspace starts a query for related objects on workspaces
func (o *Project) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	return Workspaces.Query(append(mods,
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.WorkspaceID))),
	)...)
}

func (os ProjectSlice) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
	))

	return Workspaces.Query(append(mods,
		sm.Where(psql.Group(Workspaces.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Tasks starts a query for related objects on tasks
func (o *Project) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	return Tasks.Query(append(mods,
		sm.Where(Tasks.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Tasks.Columns.ProjectID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os ProjectSlice) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Tasks.Query(append(mods,
		sm.Where(psql.Group(Tasks.Columns.WorkspaceID, Tasks.Columns.ProjectID).OP("IN", PKArgExpr)),
	)...)
}

func attachProjectWorkspace0(ctx context.Context, exec bob.Executor, count int, project0 *Project, workspace1 *Workspace) (*Project, error) {
	setter := &ProjectSetter{
		WorkspaceID: omit.From(workspace1.ID),
	}

	err := project0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectWorkspace0: %w", err)
	}

	return project0, nil
}

func (project0 *Project) InsertWorkspace(ctx context.Context, exec bob.Executor, related *WorkspaceSetter) error {
	var err error

	workspace1, err := Workspaces.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachProjectWorkspace0(ctx, exec, 1, project0, workspace1)
	if err != nil {
		return err
	}

	project0.R.Workspace = workspace1

	workspace1.R.Projects = append(workspace1.R.Projects, project0)

	return nil
}

func (project0 *Project) AttachWorkspace(ctx context.Context, exec bob.Executor, workspace1 *Workspace) error {
	var err error

	_, err = attachProjectWorkspace0(ctx, exec, 1, project0, workspace1)
	if err != nil {
		return err
	}

	project0.R.Workspace = workspace1

	workspace1.R.Projects = append(workspace1.R.Projects, project0)

	return nil
}

func insertProjectTasks0(ctx context.Context, exec bob.Executor, tasks1 []*TaskSetter, project0 *Project) (TaskSlice, error) {
	for i := range tasks1 {
		tasks1[i].WorkspaceID = omit.From(project0.WorkspaceID)
		tasks1[i].ProjectID = omit.From(project0.ID)
	}

	ret, err := Tasks.Insert(bob.ToMods(tasks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertProjectTasks0: %w", err)
	}

	return ret, nil
}

func attachProjectTasks0(ctx context.Context, exec bob.Executor, count int, tasks1 TaskSlice, project0 *Project) (TaskSlice, error) {
	setter := &TaskSetter{
		WorkspaceID: omit.From(project0.WorkspaceID),
		ProjectID:   omit.From(project0.ID),
	}

	err := tasks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachProjectTasks0: %w", err)
	}

	return tasks1, nil
}

func (project0 *Project) InsertTasks(ctx context.Context, exec bob.Executor, related ...*TaskSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tasks1, err := insertProjectTasks0(ctx, exec, related, project0)
	if err != nil {
		return err
	}

	project0.R.Tasks = append(project0.R.Tasks, tasks1...)

	for _, rel := range tasks1 {
		rel.R.Project = project0
	}
	return nil
}

func (project0 *Project) AttachTasks(ctx context.Context, exec bob.Executor, related ...*Task) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tasks1 := TaskSlice(related)

	_, err = attachProjectTasks0(ctx, exec, len(related), tasks1, project0)
	if err != nil {
		return err
	}

	project0.R.Tasks = append(project0.R.Tasks, tasks1...)

	for _, rel := range related {
		rel.R.Project = project0
	}

	return nil
}

type projectWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	WorkspaceID psql.WhereMod[Q, uuid.UUID]
	Name        psql.WhereMod[Q, string]
	Description psql.WhereMod[Q, string]
	Status      psql.WhereMod[Q, enums.ProjectStatus]
}

func (projectWhere[Q]) AliasedAs(alias string) projectWhere[Q] {
	return buildProjectWhere[Q](buildProjectColumns(alias))
}

func buildProjectWhere[Q psql.Filterable](cols projectColumns) projectWhere[Q] {
	return projectWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		WorkspaceID: psql.Where[Q, uuid.UUID](cols.WorkspaceID),
		Name:        psql.Where[Q, string](cols.Name),
		Description: psql.Where[Q, string](cols.Description),
		Status:      psql.Where[Q, enums.ProjectStatus](cols.Status),
	}
}

func (o *Project) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Workspace":
		rel, ok := retrieved.(*Workspace)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.Workspace = rel

		if rel != nil {
			rel.R.Projects = ProjectSlice{o}
		}
		return nil
	case "Tasks":
		rels, ok := retrieved.(TaskSlice)
		if !ok {
			return fmt.Errorf("project cannot load %T as %q", retrieved, name)
		}

		o.R.Tasks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Project = o
			}
		}
		return nil
	default:
		return fmt.Errorf("project has no relationship %q", name)
	}
}

type projectPreloader struct {
	Workspace func(...psql.PreloadOption) psql.Preloader
}

func buildProjectPreloader() projectPreloader {
	return projectPreloader{
		Workspace: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Workspace, WorkspaceSlice](psql.PreloadRel{
				Name: "Workspace",
				Sides: []psql.PreloadSide{
					{
						From:        Projects,
						To:          Workspaces,
						FromColumns: []string{"workspace_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Workspaces.Columns.Names(), opts...)
		},
	}
}

type projectThenLoader[Q orm.Loadable] struct {
	Workspace func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tasks     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildProjectThenLoader[Q orm.Loadable]() projectThenLoader[Q] {
	type WorkspaceLoadInterface interface {
		LoadWorkspace(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TasksLoadInterface interface {
		LoadTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return projectThenLoader[Q]{
		Workspace: thenLoadBuilder[Q](
			"Workspace",
			func(ctx context.Context, exec bob.Executor, retrieved WorkspaceLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadWorkspace(ctx, exec, mods...)
			},
		),
		Tasks: thenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadWorkspace loads the project's Workspace into the .R struct
func (o *Project) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Workspace = nil

	related, err := o.Workspace(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Projects = ProjectSlice{o}

	o.R.Workspace = related
	return nil
}

// LoadWorkspace loads the project's Workspace into the .R struct
func (os ProjectSlice) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	workspaces, err := os.Workspace(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range workspaces {

			if !(o.WorkspaceID == rel.ID) {
				continue
			}

			rel.R.Projects = append(rel.R.Projects, o)

			o.R.Workspace = rel
			break
		}
	}

	return nil
}

// LoadTasks loads the project's Tasks into the .R struct
func (o *Project) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tasks = nil

	related, err := o.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Project = o
	}

	o.R.Tasks = related
	return nil
}

// LoadTasks loads the project's Tasks into the .R struct
func (os ProjectSlice) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tasks, err := os.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Tasks = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tasks {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !(o.ID == rel.ProjectID) {
				continue
			}

			rel.R.Project = o

			o.R.Tasks = append(o.R.Tasks, rel)
		}
	}

	return nil
}

// projectC is where relationship counts are stored.
type projectC struct {
	Tasks *int64 `json:"Tasks"`
}

// PreloadCount sets a count in the C struct by name
func (o *Project) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Tasks":
		o.C.Tasks = &count
	}
	return nil
}

type projectCountPreloader struct {
	Tasks func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildProjectCountPreloader() projectCountPreloader {
	return projectCountPreloader{
		Tasks: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Project]("Tasks", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Projects.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Tasks.Name()),
					sm.Where(psql.Quote(Tasks.Alias(), "workspace_id").EQ(psql.Quote(parent, "workspace_id"))),
					sm.Where(psql.Quote(Tasks.Alias(), "project_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type projectCountThenLoader[Q orm.Loadable] struct {
	Tasks func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildProjectCountThenLoader[Q orm.Loadable]() projectCountThenLoader[Q] {
	type TasksCountInterface interface {
		LoadCountTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return projectCountThenLoader[Q]{
		Tasks: countThenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountTasks loads the count of Tasks into the C struct
func (o *Project) LoadCountTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Tasks(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Tasks = &count
	return nil
}

// LoadCountTasks loads the count of Tasks for a slice
func (os ProjectSlice) LoadCountTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountTasks(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

type projectJoins[Q dialect.Joinable] struct {
	typ       string
	Workspace modAs[Q, workspaceColumns]
	Tasks     modAs[Q, taskColumns]
}

func (j projectJoins[Q]) aliasedAs(alias string) projectJoins[Q] {
	return buildProjectJoins[Q](buildProjectColumns(alias), j.typ)
}

func buildProjectJoins[Q dialect.Joinable](cols projectColumns, typ string) projectJoins[Q] {
	return projectJoins[Q]{
		typ: typ,
		Workspace: modAs[Q, workspaceColumns]{
			c: Workspaces.Columns,
			f: func(to workspaceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Workspaces.Name().As(to.Alias())).On(
						to.ID.EQ(cols.WorkspaceID),
					))
				}

				return mods
			},
		},
		Tasks: modAs[Q, taskColumns]{
			c: Tasks.Columns,
			f: func(to taskColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tasks.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ProjectID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
