// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"
	"time"

	"github.com/aarondl/opt/null"
	"github.com/aarondl/opt/omit"
	"github.com/aarondl/opt/omitnull"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
	enums "github.com/tak848/lxgo4-bob-playground/internal/infra/dbgen/dbenums"
)

// Task is an object representing the database table.
type Task struct {
	ID          uuid.UUID           `db:"id,pk" json:"id"`
	WorkspaceID uuid.UUID           `db:"workspace_id" json:"workspace_id"`
	ProjectID   uuid.UUID           `db:"project_id" json:"project_id"`
	AssigneeID  null.Val[uuid.UUID] `db:"assignee_id" json:"assignee_id"`
	Title       string              `db:"title" json:"title"`
	Description string              `db:"description" json:"description"`
	Status      enums.TaskStatus    `db:"status" json:"status"`
	Priority    enums.TaskPriority  `db:"priority" json:"priority"`
	DueDate     null.Val[time.Time] `db:"due_date" json:"due_date"`

	R taskR `db:"-" json:"-"`

	C taskC `db:"-" json:"-"`
}

// TaskSlice is an alias for a slice of pointers to Task.
// This should almost always be used instead of []*Task.
type TaskSlice []*Task

// Tasks contains methods to work with the tasks table
var Tasks = psql.NewTablex[*Task, TaskSlice, *TaskSetter]("", "tasks", buildTaskColumns("tasks"))

// TasksQuery is a query on the tasks table
type TasksQuery = *psql.ViewQuery[*Task, TaskSlice]

// taskR is where relationships are stored.
type taskR struct {
	TaskComments TaskCommentSlice `json:"TaskComments"` // task_comments.task_comments_workspace_id_task_id_fkey
	Member       *Member          `json:"Member"`       // tasks.tasks_workspace_id_assignee_id_fkey
	Workspace    *Workspace       `json:"Workspace"`    // tasks.tasks_workspace_id_fkey
	Project      *Project         `json:"Project"`      // tasks.tasks_workspace_id_project_id_fkey
}

func buildTaskColumns(tableName string) taskColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "workspace_id", "project_id", "assignee_id", "title", "description", "status", "priority", "due_date",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return taskColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		WorkspaceID: psql.Quote(tableName, "workspace_id"),
		ProjectID:   psql.Quote(tableName, "project_id"),
		AssigneeID:  psql.Quote(tableName, "assignee_id"),
		Title:       psql.Quote(tableName, "title"),
		Description: psql.Quote(tableName, "description"),
		Status:      psql.Quote(tableName, "status"),
		Priority:    psql.Quote(tableName, "priority"),
		DueDate:     psql.Quote(tableName, "due_date"),
	}
}

type taskColumns struct {
	expr.ColumnsExpr
	tableAlias  string
	ID          psql.Expression
	WorkspaceID psql.Expression
	ProjectID   psql.Expression
	AssigneeID  psql.Expression
	Title       psql.Expression
	Description psql.Expression
	Status      psql.Expression
	Priority    psql.Expression
	DueDate     psql.Expression
}

func (c taskColumns) Alias() string {
	return c.tableAlias
}

func (taskColumns) AliasedAs(tableName string) taskColumns {
	return buildTaskColumns(tableName)
}

func (c taskColumns) Unqualified() taskColumns {
	return buildTaskColumns("")
}

// TaskSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type TaskSetter struct {
	ID          omit.Val[uuid.UUID]          `db:"id,pk" json:"id"`
	WorkspaceID omit.Val[uuid.UUID]          `db:"workspace_id" json:"workspace_id"`
	ProjectID   omit.Val[uuid.UUID]          `db:"project_id" json:"project_id"`
	AssigneeID  omitnull.Val[uuid.UUID]      `db:"assignee_id" json:"assignee_id"`
	Title       omit.Val[string]             `db:"title" json:"title"`
	Description omit.Val[string]             `db:"description" json:"description"`
	Status      omit.Val[enums.TaskStatus]   `db:"status" json:"status"`
	Priority    omit.Val[enums.TaskPriority] `db:"priority" json:"priority"`
	DueDate     omitnull.Val[time.Time]      `db:"due_date" json:"due_date"`
}

func (s TaskSetter) SetColumns() []string {
	vals := make([]string, 0, 9)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.WorkspaceID.IsValue() {
		vals = append(vals, "workspace_id")
	}
	if s.ProjectID.IsValue() {
		vals = append(vals, "project_id")
	}
	if !s.AssigneeID.IsUnset() {
		vals = append(vals, "assignee_id")
	}
	if s.Title.IsValue() {
		vals = append(vals, "title")
	}
	if s.Description.IsValue() {
		vals = append(vals, "description")
	}
	if s.Status.IsValue() {
		vals = append(vals, "status")
	}
	if s.Priority.IsValue() {
		vals = append(vals, "priority")
	}
	if !s.DueDate.IsUnset() {
		vals = append(vals, "due_date")
	}
	return vals
}

func (s TaskSetter) Overwrite(t *Task) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.WorkspaceID.IsValue() {
		t.WorkspaceID = s.WorkspaceID.MustGet()
	}
	if s.ProjectID.IsValue() {
		t.ProjectID = s.ProjectID.MustGet()
	}
	if !s.AssigneeID.IsUnset() {
		t.AssigneeID = s.AssigneeID.MustGetNull()
	}
	if s.Title.IsValue() {
		t.Title = s.Title.MustGet()
	}
	if s.Description.IsValue() {
		t.Description = s.Description.MustGet()
	}
	if s.Status.IsValue() {
		t.Status = s.Status.MustGet()
	}
	if s.Priority.IsValue() {
		t.Priority = s.Priority.MustGet()
	}
	if !s.DueDate.IsUnset() {
		t.DueDate = s.DueDate.MustGetNull()
	}
}

func (s *TaskSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Tasks.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 9)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.WorkspaceID.IsValue() {
			vals[1] = psql.Arg(s.WorkspaceID.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		if s.ProjectID.IsValue() {
			vals[2] = psql.Arg(s.ProjectID.MustGet())
		} else {
			vals[2] = psql.Raw("DEFAULT")
		}

		if !s.AssigneeID.IsUnset() {
			vals[3] = psql.Arg(s.AssigneeID.MustGetNull())
		} else {
			vals[3] = psql.Raw("DEFAULT")
		}

		if s.Title.IsValue() {
			vals[4] = psql.Arg(s.Title.MustGet())
		} else {
			vals[4] = psql.Raw("DEFAULT")
		}

		if s.Description.IsValue() {
			vals[5] = psql.Arg(s.Description.MustGet())
		} else {
			vals[5] = psql.Raw("DEFAULT")
		}

		if s.Status.IsValue() {
			vals[6] = psql.Arg(s.Status.MustGet())
		} else {
			vals[6] = psql.Raw("DEFAULT")
		}

		if s.Priority.IsValue() {
			vals[7] = psql.Arg(s.Priority.MustGet())
		} else {
			vals[7] = psql.Raw("DEFAULT")
		}

		if !s.DueDate.IsUnset() {
			vals[8] = psql.Arg(s.DueDate.MustGetNull())
		} else {
			vals[8] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s TaskSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s TaskSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 9)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.WorkspaceID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "workspace_id")...),
			psql.Arg(s.WorkspaceID),
		}})
	}

	if s.ProjectID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "project_id")...),
			psql.Arg(s.ProjectID),
		}})
	}

	if !s.AssigneeID.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "assignee_id")...),
			psql.Arg(s.AssigneeID),
		}})
	}

	if s.Title.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "title")...),
			psql.Arg(s.Title),
		}})
	}

	if s.Description.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "description")...),
			psql.Arg(s.Description),
		}})
	}

	if s.Status.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "status")...),
			psql.Arg(s.Status),
		}})
	}

	if s.Priority.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "priority")...),
			psql.Arg(s.Priority),
		}})
	}

	if !s.DueDate.IsUnset() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "due_date")...),
			psql.Arg(s.DueDate),
		}})
	}

	return exprs
}

// FindTask retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindTask(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Task, error) {
	if len(cols) == 0 {
		return Tasks.Query(
			sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Tasks.Columns.Only(cols...)),
	).One(ctx, exec)
}

// TaskExists checks the presence of a single record by primary key
func TaskExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Task is retrieved from the database
func (o *Task) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tasks.AfterSelectHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Tasks.AfterInsertHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, TaskSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, TaskSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Task
func (o *Task) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Task) pkEQ() dialect.Expression {
	return psql.Quote("tasks", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Task
func (o *Task) Update(ctx context.Context, exec bob.Executor, s *TaskSetter) error {
	v, err := Tasks.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Task record with an executor
func (o *Task) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Tasks.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Task using the executor
func (o *Task) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Tasks.Query(
		sm.Where(Tasks.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after TaskSlice is retrieved from the database
func (o TaskSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Tasks.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Tasks.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o TaskSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("tasks", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o TaskSlice) copyMatchingRows(from ...*Task) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o TaskSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tasks.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Task:
				o.copyMatchingRows(retrieved)
			case []*Task:
				o.copyMatchingRows(retrieved...)
			case TaskSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Task or a slice of Task
				// then run the AfterUpdateHooks on the slice
				_, err = Tasks.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o TaskSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Tasks.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Task:
				o.copyMatchingRows(retrieved)
			case []*Task:
				o.copyMatchingRows(retrieved...)
			case TaskSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Task or a slice of Task
				// then run the AfterDeleteHooks on the slice
				_, err = Tasks.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o TaskSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals TaskSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tasks.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o TaskSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Tasks.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o TaskSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Tasks.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// TaskComments starts a query for related objects on task_comments
func (o *Task) TaskComments(mods ...bob.Mod[*dialect.SelectQuery]) TaskCommentsQuery {
	return TaskComments.Query(append(mods,
		sm.Where(TaskComments.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(TaskComments.Columns.TaskID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os TaskSlice) TaskComments(mods ...bob.Mod[*dialect.SelectQuery]) TaskCommentsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return TaskComments.Query(append(mods,
		sm.Where(psql.Group(TaskComments.Columns.WorkspaceID, TaskComments.Columns.TaskID).OP("IN", PKArgExpr)),
	)...)
}

// Member starts a query for related objects on members
func (o *Task) Member(mods ...bob.Mod[*dialect.SelectQuery]) MembersQuery {
	return Members.Query(append(mods,
		sm.Where(Members.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Members.Columns.ID.EQ(psql.Arg(o.AssigneeID))),
	)...)
}

func (os TaskSlice) Member(mods ...bob.Mod[*dialect.SelectQuery]) MembersQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkAssigneeID := make(pgtypes.Array[null.Val[uuid.UUID]], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkAssigneeID = append(pkAssigneeID, o.AssigneeID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkAssigneeID), "uuid[]")),
	))

	return Members.Query(append(mods,
		sm.Where(psql.Group(Members.Columns.WorkspaceID, Members.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Workspace starts a query for related objects on workspaces
func (o *Task) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	return Workspaces.Query(append(mods,
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.WorkspaceID))),
	)...)
}

func (os TaskSlice) Workspace(mods ...bob.Mod[*dialect.SelectQuery]) WorkspacesQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
	))

	return Workspaces.Query(append(mods,
		sm.Where(psql.Group(Workspaces.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

// Project starts a query for related objects on projects
func (o *Task) Project(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	return Projects.Query(append(mods,
		sm.Where(Projects.Columns.WorkspaceID.EQ(psql.Arg(o.WorkspaceID))), sm.Where(Projects.Columns.ID.EQ(psql.Arg(o.ProjectID))),
	)...)
}

func (os TaskSlice) Project(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	pkWorkspaceID := make(pgtypes.Array[uuid.UUID], 0, len(os))

	pkProjectID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkWorkspaceID = append(pkWorkspaceID, o.WorkspaceID)
		pkProjectID = append(pkProjectID, o.ProjectID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkWorkspaceID), "uuid[]")),
		psql.F("unnest", psql.Cast(psql.Arg(pkProjectID), "uuid[]")),
	))

	return Projects.Query(append(mods,
		sm.Where(psql.Group(Projects.Columns.WorkspaceID, Projects.Columns.ID).OP("IN", PKArgExpr)),
	)...)
}

func insertTaskTaskComments0(ctx context.Context, exec bob.Executor, taskComments1 []*TaskCommentSetter, task0 *Task) (TaskCommentSlice, error) {
	for i := range taskComments1 {
		taskComments1[i].WorkspaceID = omit.From(task0.WorkspaceID)
		taskComments1[i].TaskID = omit.From(task0.ID)
	}

	ret, err := TaskComments.Insert(bob.ToMods(taskComments1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertTaskTaskComments0: %w", err)
	}

	return ret, nil
}

func attachTaskTaskComments0(ctx context.Context, exec bob.Executor, count int, taskComments1 TaskCommentSlice, task0 *Task) (TaskCommentSlice, error) {
	setter := &TaskCommentSetter{
		WorkspaceID: omit.From(task0.WorkspaceID),
		TaskID:      omit.From(task0.ID),
	}

	err := taskComments1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskTaskComments0: %w", err)
	}

	return taskComments1, nil
}

func (task0 *Task) InsertTaskComments(ctx context.Context, exec bob.Executor, related ...*TaskCommentSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	taskComments1, err := insertTaskTaskComments0(ctx, exec, related, task0)
	if err != nil {
		return err
	}

	task0.R.TaskComments = append(task0.R.TaskComments, taskComments1...)

	for _, rel := range taskComments1 {
		rel.R.Task = task0
	}
	return nil
}

func (task0 *Task) AttachTaskComments(ctx context.Context, exec bob.Executor, related ...*TaskComment) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	taskComments1 := TaskCommentSlice(related)

	_, err = attachTaskTaskComments0(ctx, exec, len(related), taskComments1, task0)
	if err != nil {
		return err
	}

	task0.R.TaskComments = append(task0.R.TaskComments, taskComments1...)

	for _, rel := range related {
		rel.R.Task = task0
	}

	return nil
}

func attachTaskMember0(ctx context.Context, exec bob.Executor, count int, task0 *Task, member1 *Member) (*Task, error) {
	setter := &TaskSetter{
		WorkspaceID: omit.From(member1.WorkspaceID),
		AssigneeID:  omitnull.From(member1.ID),
	}

	err := task0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskMember0: %w", err)
	}

	return task0, nil
}

func (task0 *Task) InsertMember(ctx context.Context, exec bob.Executor, related *MemberSetter) error {
	var err error

	member1, err := Members.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTaskMember0(ctx, exec, 1, task0, member1)
	if err != nil {
		return err
	}

	task0.R.Member = member1

	member1.R.Tasks = append(member1.R.Tasks, task0)

	return nil
}

func (task0 *Task) AttachMember(ctx context.Context, exec bob.Executor, member1 *Member) error {
	var err error

	_, err = attachTaskMember0(ctx, exec, 1, task0, member1)
	if err != nil {
		return err
	}

	task0.R.Member = member1

	member1.R.Tasks = append(member1.R.Tasks, task0)

	return nil
}

func attachTaskWorkspace0(ctx context.Context, exec bob.Executor, count int, task0 *Task, workspace1 *Workspace) (*Task, error) {
	setter := &TaskSetter{
		WorkspaceID: omit.From(workspace1.ID),
	}

	err := task0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskWorkspace0: %w", err)
	}

	return task0, nil
}

func (task0 *Task) InsertWorkspace(ctx context.Context, exec bob.Executor, related *WorkspaceSetter) error {
	var err error

	workspace1, err := Workspaces.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTaskWorkspace0(ctx, exec, 1, task0, workspace1)
	if err != nil {
		return err
	}

	task0.R.Workspace = workspace1

	workspace1.R.Tasks = append(workspace1.R.Tasks, task0)

	return nil
}

func (task0 *Task) AttachWorkspace(ctx context.Context, exec bob.Executor, workspace1 *Workspace) error {
	var err error

	_, err = attachTaskWorkspace0(ctx, exec, 1, task0, workspace1)
	if err != nil {
		return err
	}

	task0.R.Workspace = workspace1

	workspace1.R.Tasks = append(workspace1.R.Tasks, task0)

	return nil
}

func attachTaskProject0(ctx context.Context, exec bob.Executor, count int, task0 *Task, project1 *Project) (*Task, error) {
	setter := &TaskSetter{
		WorkspaceID: omit.From(project1.WorkspaceID),
		ProjectID:   omit.From(project1.ID),
	}

	err := task0.Update(ctx, exec, setter)
	if err != nil {
		return nil, fmt.Errorf("attachTaskProject0: %w", err)
	}

	return task0, nil
}

func (task0 *Task) InsertProject(ctx context.Context, exec bob.Executor, related *ProjectSetter) error {
	var err error

	project1, err := Projects.Insert(related).One(ctx, exec)
	if err != nil {
		return fmt.Errorf("inserting related objects: %w", err)
	}

	_, err = attachTaskProject0(ctx, exec, 1, task0, project1)
	if err != nil {
		return err
	}

	task0.R.Project = project1

	project1.R.Tasks = append(project1.R.Tasks, task0)

	return nil
}

func (task0 *Task) AttachProject(ctx context.Context, exec bob.Executor, project1 *Project) error {
	var err error

	_, err = attachTaskProject0(ctx, exec, 1, task0, project1)
	if err != nil {
		return err
	}

	task0.R.Project = project1

	project1.R.Tasks = append(project1.R.Tasks, task0)

	return nil
}

type taskWhere[Q psql.Filterable] struct {
	ID          psql.WhereMod[Q, uuid.UUID]
	WorkspaceID psql.WhereMod[Q, uuid.UUID]
	ProjectID   psql.WhereMod[Q, uuid.UUID]
	AssigneeID  psql.WhereNullMod[Q, uuid.UUID]
	Title       psql.WhereMod[Q, string]
	Description psql.WhereMod[Q, string]
	Status      psql.WhereMod[Q, enums.TaskStatus]
	Priority    psql.WhereMod[Q, enums.TaskPriority]
	DueDate     psql.WhereNullMod[Q, time.Time]
}

func (taskWhere[Q]) AliasedAs(alias string) taskWhere[Q] {
	return buildTaskWhere[Q](buildTaskColumns(alias))
}

func buildTaskWhere[Q psql.Filterable](cols taskColumns) taskWhere[Q] {
	return taskWhere[Q]{
		ID:          psql.Where[Q, uuid.UUID](cols.ID),
		WorkspaceID: psql.Where[Q, uuid.UUID](cols.WorkspaceID),
		ProjectID:   psql.Where[Q, uuid.UUID](cols.ProjectID),
		AssigneeID:  psql.WhereNull[Q, uuid.UUID](cols.AssigneeID),
		Title:       psql.Where[Q, string](cols.Title),
		Description: psql.Where[Q, string](cols.Description),
		Status:      psql.Where[Q, enums.TaskStatus](cols.Status),
		Priority:    psql.Where[Q, enums.TaskPriority](cols.Priority),
		DueDate:     psql.WhereNull[Q, time.Time](cols.DueDate),
	}
}

func (o *Task) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TaskComments":
		rels, ok := retrieved.(TaskCommentSlice)
		if !ok {
			return fmt.Errorf("task cannot load %T as %q", retrieved, name)
		}

		o.R.TaskComments = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Task = o
			}
		}
		return nil
	case "Member":
		rel, ok := retrieved.(*Member)
		if !ok {
			return fmt.Errorf("task cannot load %T as %q", retrieved, name)
		}

		o.R.Member = rel

		if rel != nil {
			rel.R.Tasks = TaskSlice{o}
		}
		return nil
	case "Workspace":
		rel, ok := retrieved.(*Workspace)
		if !ok {
			return fmt.Errorf("task cannot load %T as %q", retrieved, name)
		}

		o.R.Workspace = rel

		if rel != nil {
			rel.R.Tasks = TaskSlice{o}
		}
		return nil
	case "Project":
		rel, ok := retrieved.(*Project)
		if !ok {
			return fmt.Errorf("task cannot load %T as %q", retrieved, name)
		}

		o.R.Project = rel

		if rel != nil {
			rel.R.Tasks = TaskSlice{o}
		}
		return nil
	default:
		return fmt.Errorf("task has no relationship %q", name)
	}
}

type taskPreloader struct {
	Member    func(...psql.PreloadOption) psql.Preloader
	Workspace func(...psql.PreloadOption) psql.Preloader
	Project   func(...psql.PreloadOption) psql.Preloader
}

func buildTaskPreloader() taskPreloader {
	return taskPreloader{
		Member: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Member, MemberSlice](psql.PreloadRel{
				Name: "Member",
				Sides: []psql.PreloadSide{
					{
						From:        Tasks,
						To:          Members,
						FromColumns: []string{"workspace_id", "assignee_id"},
						ToColumns:   []string{"workspace_id", "id"},
					},
				},
			}, Members.Columns.Names(), opts...)
		},
		Workspace: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Workspace, WorkspaceSlice](psql.PreloadRel{
				Name: "Workspace",
				Sides: []psql.PreloadSide{
					{
						From:        Tasks,
						To:          Workspaces,
						FromColumns: []string{"workspace_id"},
						ToColumns:   []string{"id"},
					},
				},
			}, Workspaces.Columns.Names(), opts...)
		},
		Project: func(opts ...psql.PreloadOption) psql.Preloader {
			return psql.Preload[*Project, ProjectSlice](psql.PreloadRel{
				Name: "Project",
				Sides: []psql.PreloadSide{
					{
						From:        Tasks,
						To:          Projects,
						FromColumns: []string{"workspace_id", "project_id"},
						ToColumns:   []string{"workspace_id", "id"},
					},
				},
			}, Projects.Columns.Names(), opts...)
		},
	}
}

type taskThenLoader[Q orm.Loadable] struct {
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Member       func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Workspace    func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Project      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTaskThenLoader[Q orm.Loadable]() taskThenLoader[Q] {
	type TaskCommentsLoadInterface interface {
		LoadTaskComments(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type MemberLoadInterface interface {
		LoadMember(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type WorkspaceLoadInterface interface {
		LoadWorkspace(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProjectLoadInterface interface {
		LoadProject(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return taskThenLoader[Q]{
		TaskComments: thenLoadBuilder[Q](
			"TaskComments",
			func(ctx context.Context, exec bob.Executor, retrieved TaskCommentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTaskComments(ctx, exec, mods...)
			},
		),
		Member: thenLoadBuilder[Q](
			"Member",
			func(ctx context.Context, exec bob.Executor, retrieved MemberLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMember(ctx, exec, mods...)
			},
		),
		Workspace: thenLoadBuilder[Q](
			"Workspace",
			func(ctx context.Context, exec bob.Executor, retrieved WorkspaceLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadWorkspace(ctx, exec, mods...)
			},
		),
		Project: thenLoadBuilder[Q](
			"Project",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProject(ctx, exec, mods...)
			},
		),
	}
}

// LoadTaskComments loads the task's TaskComments into the .R struct
func (o *Task) LoadTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TaskComments = nil

	related, err := o.TaskComments(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Task = o
	}

	o.R.TaskComments = related
	return nil
}

// LoadTaskComments loads the task's TaskComments into the .R struct
func (os TaskSlice) LoadTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	taskComments, err := os.TaskComments(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TaskComments = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range taskComments {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !(o.ID == rel.TaskID) {
				continue
			}

			rel.R.Task = o

			o.R.TaskComments = append(o.R.TaskComments, rel)
		}
	}

	return nil
}

// LoadMember loads the task's Member into the .R struct
func (o *Task) LoadMember(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Member = nil

	related, err := o.Member(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Tasks = TaskSlice{o}

	o.R.Member = related
	return nil
}

// LoadMember loads the task's Member into the .R struct
func (os TaskSlice) LoadMember(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	members, err := os.Member(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range members {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}
			if !o.AssigneeID.IsValue() {
				continue
			}

			if !(o.AssigneeID.IsValue() && o.AssigneeID.MustGet() == rel.ID) {
				continue
			}

			rel.R.Tasks = append(rel.R.Tasks, o)

			o.R.Member = rel
			break
		}
	}

	return nil
}

// LoadWorkspace loads the task's Workspace into the .R struct
func (o *Task) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Workspace = nil

	related, err := o.Workspace(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Tasks = TaskSlice{o}

	o.R.Workspace = related
	return nil
}

// LoadWorkspace loads the task's Workspace into the .R struct
func (os TaskSlice) LoadWorkspace(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	workspaces, err := os.Workspace(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range workspaces {

			if !(o.WorkspaceID == rel.ID) {
				continue
			}

			rel.R.Tasks = append(rel.R.Tasks, o)

			o.R.Workspace = rel
			break
		}
	}

	return nil
}

// LoadProject loads the task's Project into the .R struct
func (o *Task) LoadProject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Project = nil

	related, err := o.Project(mods...).One(ctx, exec)
	if err != nil {
		return err
	}

	related.R.Tasks = TaskSlice{o}

	o.R.Project = related
	return nil
}

// LoadProject loads the task's Project into the .R struct
func (os TaskSlice) LoadProject(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	projects, err := os.Project(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range projects {

			if !(o.WorkspaceID == rel.WorkspaceID) {
				continue
			}

			if !(o.ProjectID == rel.ID) {
				continue
			}

			rel.R.Tasks = append(rel.R.Tasks, o)

			o.R.Project = rel
			break
		}
	}

	return nil
}

// taskC is where relationship counts are stored.
type taskC struct {
	TaskComments *int64 `json:"TaskComments"`
}

// PreloadCount sets a count in the C struct by name
func (o *Task) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "TaskComments":
		o.C.TaskComments = &count
	}
	return nil
}

type taskCountPreloader struct {
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildTaskCountPreloader() taskCountPreloader {
	return taskCountPreloader{
		TaskComments: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Task]("TaskComments", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Tasks.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(TaskComments.Name()),
					sm.Where(psql.Quote(TaskComments.Alias(), "workspace_id").EQ(psql.Quote(parent, "workspace_id"))),
					sm.Where(psql.Quote(TaskComments.Alias(), "task_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type taskCountThenLoader[Q orm.Loadable] struct {
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildTaskCountThenLoader[Q orm.Loadable]() taskCountThenLoader[Q] {
	type TaskCommentsCountInterface interface {
		LoadCountTaskComments(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return taskCountThenLoader[Q]{
		TaskComments: countThenLoadBuilder[Q](
			"TaskComments",
			func(ctx context.Context, exec bob.Executor, retrieved TaskCommentsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTaskComments(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountTaskComments loads the count of TaskComments into the C struct
func (o *Task) LoadCountTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TaskComments(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TaskComments = &count
	return nil
}

// LoadCountTaskComments loads the count of TaskComments for a slice
func (os TaskSlice) LoadCountTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountTaskComments(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

type taskJoins[Q dialect.Joinable] struct {
	typ          string
	TaskComments modAs[Q, taskCommentColumns]
	Member       modAs[Q, memberColumns]
	Workspace    modAs[Q, workspaceColumns]
	Project      modAs[Q, projectColumns]
}

func (j taskJoins[Q]) aliasedAs(alias string) taskJoins[Q] {
	return buildTaskJoins[Q](buildTaskColumns(alias), j.typ)
}

func buildTaskJoins[Q dialect.Joinable](cols taskColumns, typ string) taskJoins[Q] {
	return taskJoins[Q]{
		typ: typ,
		TaskComments: modAs[Q, taskCommentColumns]{
			c: TaskComments.Columns,
			f: func(to taskCommentColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TaskComments.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.TaskID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Member: modAs[Q, memberColumns]{
			c: Members.Columns,
			f: func(to memberColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Members.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ID.EQ(cols.AssigneeID),
					))
				}

				return mods
			},
		},
		Workspace: modAs[Q, workspaceColumns]{
			c: Workspaces.Columns,
			f: func(to workspaceColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Workspaces.Name().As(to.Alias())).On(
						to.ID.EQ(cols.WorkspaceID),
					))
				}

				return mods
			},
		},
		Project: modAs[Q, projectColumns]{
			c: Projects.Columns,
			f: func(to projectColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Projects.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.WorkspaceID), to.ID.EQ(cols.ProjectID),
					))
				}

				return mods
			},
		},
	}
}
