// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbgen

import (
	"context"
	"fmt"
	"io"

	"github.com/aarondl/opt/omit"
	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/dialect/psql"
	"github.com/stephenafamo/bob/dialect/psql/dialect"
	"github.com/stephenafamo/bob/dialect/psql/dm"
	"github.com/stephenafamo/bob/dialect/psql/sm"
	"github.com/stephenafamo/bob/dialect/psql/um"
	"github.com/stephenafamo/bob/expr"
	"github.com/stephenafamo/bob/mods"
	"github.com/stephenafamo/bob/orm"
	"github.com/stephenafamo/bob/types/pgtypes"
)

// Workspace is an object representing the database table.
type Workspace struct {
	ID   uuid.UUID `db:"id,pk" json:"id"`
	Name string    `db:"name" json:"name"`

	R workspaceR `db:"-" json:"-"`

	C workspaceC `db:"-" json:"-"`
}

// WorkspaceSlice is an alias for a slice of pointers to Workspace.
// This should almost always be used instead of []*Workspace.
type WorkspaceSlice []*Workspace

// Workspaces contains methods to work with the workspaces table
var Workspaces = psql.NewTablex[*Workspace, WorkspaceSlice, *WorkspaceSetter]("", "workspaces", buildWorkspaceColumns("workspaces"))

// WorkspacesQuery is a query on the workspaces table
type WorkspacesQuery = *psql.ViewQuery[*Workspace, WorkspaceSlice]

// workspaceR is where relationships are stored.
type workspaceR struct {
	Members      MemberSlice      `json:"Members"`      // members.members_workspace_id_fkey
	Projects     ProjectSlice     `json:"Projects"`     // projects.projects_workspace_id_fkey
	TaskComments TaskCommentSlice `json:"TaskComments"` // task_comments.task_comments_workspace_id_fkey
	Tasks        TaskSlice        `json:"Tasks"`        // tasks.tasks_workspace_id_fkey
}

func buildWorkspaceColumns(tableName string) workspaceColumns {
	columnsExpr := expr.NewColumnsExpr(
		"id", "name",
	)
	if tableName != "" {
		columnsExpr = columnsExpr.WithParent(tableName)
	}
	return workspaceColumns{
		ColumnsExpr: columnsExpr,
		tableAlias:  tableName,
		ID:          psql.Quote(tableName, "id"),
		Name:        psql.Quote(tableName, "name"),
	}
}

type workspaceColumns struct {
	expr.ColumnsExpr
	tableAlias string
	ID         psql.Expression
	Name       psql.Expression
}

func (c workspaceColumns) Alias() string {
	return c.tableAlias
}

func (workspaceColumns) AliasedAs(tableName string) workspaceColumns {
	return buildWorkspaceColumns(tableName)
}

func (c workspaceColumns) Unqualified() workspaceColumns {
	return buildWorkspaceColumns("")
}

// WorkspaceSetter is used for insert/upsert/update operations
// All values are optional, and do not have to be set
// Generated columns are not included
type WorkspaceSetter struct {
	ID   omit.Val[uuid.UUID] `db:"id,pk" json:"id"`
	Name omit.Val[string]    `db:"name" json:"name"`
}

func (s WorkspaceSetter) SetColumns() []string {
	vals := make([]string, 0, 2)
	if s.ID.IsValue() {
		vals = append(vals, "id")
	}
	if s.Name.IsValue() {
		vals = append(vals, "name")
	}
	return vals
}

func (s WorkspaceSetter) Overwrite(t *Workspace) {
	if s.ID.IsValue() {
		t.ID = s.ID.MustGet()
	}
	if s.Name.IsValue() {
		t.Name = s.Name.MustGet()
	}
}

func (s *WorkspaceSetter) Apply(q *dialect.InsertQuery) {
	q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
		return Workspaces.BeforeInsertHooks.RunHooks(ctx, exec, s)
	})

	q.AppendValues(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		vals := make([]bob.Expression, 2)
		if s.ID.IsValue() {
			vals[0] = psql.Arg(s.ID.MustGet())
		} else {
			vals[0] = psql.Raw("DEFAULT")
		}

		if s.Name.IsValue() {
			vals[1] = psql.Arg(s.Name.MustGet())
		} else {
			vals[1] = psql.Raw("DEFAULT")
		}

		return bob.ExpressSlice(ctx, w, d, start, vals, "", ", ", "")
	}))
}

func (s WorkspaceSetter) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return um.Set(s.Expressions()...)
}

func (s WorkspaceSetter) Expressions(prefix ...string) []bob.Expression {
	exprs := make([]bob.Expression, 0, 2)

	if s.ID.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "id")...),
			psql.Arg(s.ID),
		}})
	}

	if s.Name.IsValue() {
		exprs = append(exprs, expr.Join{Sep: " = ", Exprs: []bob.Expression{
			psql.Quote(append(prefix, "name")...),
			psql.Arg(s.Name),
		}})
	}

	return exprs
}

// FindWorkspace retrieves a single record by primary key
// If cols is empty Find will return all columns.
func FindWorkspace(ctx context.Context, exec bob.Executor, IDPK uuid.UUID, cols ...string) (*Workspace, error) {
	if len(cols) == 0 {
		return Workspaces.Query(
			sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(IDPK))),
		).One(ctx, exec)
	}

	return Workspaces.Query(
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(IDPK))),
		sm.Columns(Workspaces.Columns.Only(cols...)),
	).One(ctx, exec)
}

// WorkspaceExists checks the presence of a single record by primary key
func WorkspaceExists(ctx context.Context, exec bob.Executor, IDPK uuid.UUID) (bool, error) {
	return Workspaces.Query(
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(IDPK))),
	).Exists(ctx, exec)
}

// AfterQueryHook is called after Workspace is retrieved from the database
func (o *Workspace) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Workspaces.AfterSelectHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	case bob.QueryTypeInsert:
		ctx, err = Workspaces.AfterInsertHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	case bob.QueryTypeUpdate:
		ctx, err = Workspaces.AfterUpdateHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	case bob.QueryTypeDelete:
		ctx, err = Workspaces.AfterDeleteHooks.RunHooks(ctx, exec, WorkspaceSlice{o})
	}

	return err
}

// primaryKeyVals returns the primary key values of the Workspace
func (o *Workspace) primaryKeyVals() bob.Expression {
	return psql.Arg(o.ID)
}

func (o *Workspace) pkEQ() dialect.Expression {
	return psql.Quote("workspaces", "id").EQ(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		return o.primaryKeyVals().WriteSQL(ctx, w, d, start)
	}))
}

// Update uses an executor to update the Workspace
func (o *Workspace) Update(ctx context.Context, exec bob.Executor, s *WorkspaceSetter) error {
	v, err := Workspaces.Update(s.UpdateMod(), um.Where(o.pkEQ())).One(ctx, exec)
	if err != nil {
		return err
	}

	o.R = v.R
	*o = *v

	return nil
}

// Delete deletes a single Workspace record with an executor
func (o *Workspace) Delete(ctx context.Context, exec bob.Executor) error {
	_, err := Workspaces.Delete(dm.Where(o.pkEQ())).Exec(ctx, exec)
	return err
}

// Reload refreshes the Workspace using the executor
func (o *Workspace) Reload(ctx context.Context, exec bob.Executor) error {
	o2, err := Workspaces.Query(
		sm.Where(Workspaces.Columns.ID.EQ(psql.Arg(o.ID))),
	).One(ctx, exec)
	if err != nil {
		return err
	}
	o2.R = o.R
	*o = *o2

	return nil
}

// AfterQueryHook is called after WorkspaceSlice is retrieved from the database
func (o WorkspaceSlice) AfterQueryHook(ctx context.Context, exec bob.Executor, queryType bob.QueryType) error {
	var err error

	switch queryType {
	case bob.QueryTypeSelect:
		ctx, err = Workspaces.AfterSelectHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeInsert:
		ctx, err = Workspaces.AfterInsertHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeUpdate:
		ctx, err = Workspaces.AfterUpdateHooks.RunHooks(ctx, exec, o)
	case bob.QueryTypeDelete:
		ctx, err = Workspaces.AfterDeleteHooks.RunHooks(ctx, exec, o)
	}

	return err
}

func (o WorkspaceSlice) pkIN() dialect.Expression {
	if len(o) == 0 {
		return psql.Raw("NULL")
	}

	return psql.Quote("workspaces", "id").In(bob.ExpressionFunc(func(ctx context.Context, w io.StringWriter, d bob.Dialect, start int) ([]any, error) {
		pkPairs := make([]bob.Expression, len(o))
		for i, row := range o {
			pkPairs[i] = row.primaryKeyVals()
		}
		return bob.ExpressSlice(ctx, w, d, start, pkPairs, "", ", ", "")
	}))
}

// copyMatchingRows finds models in the given slice that have the same primary key
// then it first copies the existing relationships from the old model to the new model
// and then replaces the old model in the slice with the new model
func (o WorkspaceSlice) copyMatchingRows(from ...*Workspace) {
	for i, old := range o {
		for _, new := range from {
			if new.ID != old.ID {
				continue
			}
			new.R = old.R
			o[i] = new
			break
		}
	}
}

// UpdateMod modifies an update query with "WHERE primary_key IN (o...)"
func (o WorkspaceSlice) UpdateMod() bob.Mod[*dialect.UpdateQuery] {
	return bob.ModFunc[*dialect.UpdateQuery](func(q *dialect.UpdateQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Workspaces.BeforeUpdateHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Workspace:
				o.copyMatchingRows(retrieved)
			case []*Workspace:
				o.copyMatchingRows(retrieved...)
			case WorkspaceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Workspace or a slice of Workspace
				// then run the AfterUpdateHooks on the slice
				_, err = Workspaces.AfterUpdateHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

// DeleteMod modifies an delete query with "WHERE primary_key IN (o...)"
func (o WorkspaceSlice) DeleteMod() bob.Mod[*dialect.DeleteQuery] {
	return bob.ModFunc[*dialect.DeleteQuery](func(q *dialect.DeleteQuery) {
		q.AppendHooks(func(ctx context.Context, exec bob.Executor) (context.Context, error) {
			return Workspaces.BeforeDeleteHooks.RunHooks(ctx, exec, o)
		})

		q.AppendLoader(bob.LoaderFunc(func(ctx context.Context, exec bob.Executor, retrieved any) error {
			var err error
			switch retrieved := retrieved.(type) {
			case *Workspace:
				o.copyMatchingRows(retrieved)
			case []*Workspace:
				o.copyMatchingRows(retrieved...)
			case WorkspaceSlice:
				o.copyMatchingRows(retrieved...)
			default:
				// If the retrieved value is not a Workspace or a slice of Workspace
				// then run the AfterDeleteHooks on the slice
				_, err = Workspaces.AfterDeleteHooks.RunHooks(ctx, exec, o)
			}

			return err
		}))

		q.AppendWhere(o.pkIN())
	})
}

func (o WorkspaceSlice) UpdateAll(ctx context.Context, exec bob.Executor, vals WorkspaceSetter) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Workspaces.Update(vals.UpdateMod(), o.UpdateMod()).All(ctx, exec)
	return err
}

func (o WorkspaceSlice) DeleteAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	_, err := Workspaces.Delete(o.DeleteMod()).Exec(ctx, exec)
	return err
}

func (o WorkspaceSlice) ReloadAll(ctx context.Context, exec bob.Executor) error {
	if len(o) == 0 {
		return nil
	}

	o2, err := Workspaces.Query(sm.Where(o.pkIN())).All(ctx, exec)
	if err != nil {
		return err
	}

	o.copyMatchingRows(o2...)

	return nil
}

// Members starts a query for related objects on members
func (o *Workspace) Members(mods ...bob.Mod[*dialect.SelectQuery]) MembersQuery {
	return Members.Query(append(mods,
		sm.Where(Members.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Members(mods ...bob.Mod[*dialect.SelectQuery]) MembersQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Members.Query(append(mods,
		sm.Where(psql.Group(Members.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

// Projects starts a query for related objects on projects
func (o *Workspace) Projects(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	return Projects.Query(append(mods,
		sm.Where(Projects.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Projects(mods ...bob.Mod[*dialect.SelectQuery]) ProjectsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Projects.Query(append(mods,
		sm.Where(psql.Group(Projects.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

// TaskComments starts a query for related objects on task_comments
func (o *Workspace) TaskComments(mods ...bob.Mod[*dialect.SelectQuery]) TaskCommentsQuery {
	return TaskComments.Query(append(mods,
		sm.Where(TaskComments.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) TaskComments(mods ...bob.Mod[*dialect.SelectQuery]) TaskCommentsQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return TaskComments.Query(append(mods,
		sm.Where(psql.Group(TaskComments.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

// Tasks starts a query for related objects on tasks
func (o *Workspace) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	return Tasks.Query(append(mods,
		sm.Where(Tasks.Columns.WorkspaceID.EQ(psql.Arg(o.ID))),
	)...)
}

func (os WorkspaceSlice) Tasks(mods ...bob.Mod[*dialect.SelectQuery]) TasksQuery {
	pkID := make(pgtypes.Array[uuid.UUID], 0, len(os))
	for _, o := range os {
		if o == nil {
			continue
		}
		pkID = append(pkID, o.ID)
	}
	PKArgExpr := psql.Select(sm.Columns(
		psql.F("unnest", psql.Cast(psql.Arg(pkID), "uuid[]")),
	))

	return Tasks.Query(append(mods,
		sm.Where(psql.Group(Tasks.Columns.WorkspaceID).OP("IN", PKArgExpr)),
	)...)
}

func insertWorkspaceMembers0(ctx context.Context, exec bob.Executor, members1 []*MemberSetter, workspace0 *Workspace) (MemberSlice, error) {
	for i := range members1 {
		members1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Members.Insert(bob.ToMods(members1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceMembers0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceMembers0(ctx context.Context, exec bob.Executor, count int, members1 MemberSlice, workspace0 *Workspace) (MemberSlice, error) {
	setter := &MemberSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := members1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceMembers0: %w", err)
	}

	return members1, nil
}

func (workspace0 *Workspace) InsertMembers(ctx context.Context, exec bob.Executor, related ...*MemberSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	members1, err := insertWorkspaceMembers0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Members = append(workspace0.R.Members, members1...)

	for _, rel := range members1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachMembers(ctx context.Context, exec bob.Executor, related ...*Member) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	members1 := MemberSlice(related)

	_, err = attachWorkspaceMembers0(ctx, exec, len(related), members1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Members = append(workspace0.R.Members, members1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

func insertWorkspaceProjects0(ctx context.Context, exec bob.Executor, projects1 []*ProjectSetter, workspace0 *Workspace) (ProjectSlice, error) {
	for i := range projects1 {
		projects1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Projects.Insert(bob.ToMods(projects1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceProjects0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceProjects0(ctx context.Context, exec bob.Executor, count int, projects1 ProjectSlice, workspace0 *Workspace) (ProjectSlice, error) {
	setter := &ProjectSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := projects1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceProjects0: %w", err)
	}

	return projects1, nil
}

func (workspace0 *Workspace) InsertProjects(ctx context.Context, exec bob.Executor, related ...*ProjectSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	projects1, err := insertWorkspaceProjects0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Projects = append(workspace0.R.Projects, projects1...)

	for _, rel := range projects1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachProjects(ctx context.Context, exec bob.Executor, related ...*Project) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	projects1 := ProjectSlice(related)

	_, err = attachWorkspaceProjects0(ctx, exec, len(related), projects1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Projects = append(workspace0.R.Projects, projects1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

func insertWorkspaceTaskComments0(ctx context.Context, exec bob.Executor, taskComments1 []*TaskCommentSetter, workspace0 *Workspace) (TaskCommentSlice, error) {
	for i := range taskComments1 {
		taskComments1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := TaskComments.Insert(bob.ToMods(taskComments1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceTaskComments0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceTaskComments0(ctx context.Context, exec bob.Executor, count int, taskComments1 TaskCommentSlice, workspace0 *Workspace) (TaskCommentSlice, error) {
	setter := &TaskCommentSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := taskComments1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceTaskComments0: %w", err)
	}

	return taskComments1, nil
}

func (workspace0 *Workspace) InsertTaskComments(ctx context.Context, exec bob.Executor, related ...*TaskCommentSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	taskComments1, err := insertWorkspaceTaskComments0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.TaskComments = append(workspace0.R.TaskComments, taskComments1...)

	for _, rel := range taskComments1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachTaskComments(ctx context.Context, exec bob.Executor, related ...*TaskComment) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	taskComments1 := TaskCommentSlice(related)

	_, err = attachWorkspaceTaskComments0(ctx, exec, len(related), taskComments1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.TaskComments = append(workspace0.R.TaskComments, taskComments1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

func insertWorkspaceTasks0(ctx context.Context, exec bob.Executor, tasks1 []*TaskSetter, workspace0 *Workspace) (TaskSlice, error) {
	for i := range tasks1 {
		tasks1[i].WorkspaceID = omit.From(workspace0.ID)
	}

	ret, err := Tasks.Insert(bob.ToMods(tasks1...)).All(ctx, exec)
	if err != nil {
		return ret, fmt.Errorf("insertWorkspaceTasks0: %w", err)
	}

	return ret, nil
}

func attachWorkspaceTasks0(ctx context.Context, exec bob.Executor, count int, tasks1 TaskSlice, workspace0 *Workspace) (TaskSlice, error) {
	setter := &TaskSetter{
		WorkspaceID: omit.From(workspace0.ID),
	}

	err := tasks1.UpdateAll(ctx, exec, *setter)
	if err != nil {
		return nil, fmt.Errorf("attachWorkspaceTasks0: %w", err)
	}

	return tasks1, nil
}

func (workspace0 *Workspace) InsertTasks(ctx context.Context, exec bob.Executor, related ...*TaskSetter) error {
	if len(related) == 0 {
		return nil
	}

	var err error

	tasks1, err := insertWorkspaceTasks0(ctx, exec, related, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Tasks = append(workspace0.R.Tasks, tasks1...)

	for _, rel := range tasks1 {
		rel.R.Workspace = workspace0
	}
	return nil
}

func (workspace0 *Workspace) AttachTasks(ctx context.Context, exec bob.Executor, related ...*Task) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	tasks1 := TaskSlice(related)

	_, err = attachWorkspaceTasks0(ctx, exec, len(related), tasks1, workspace0)
	if err != nil {
		return err
	}

	workspace0.R.Tasks = append(workspace0.R.Tasks, tasks1...)

	for _, rel := range related {
		rel.R.Workspace = workspace0
	}

	return nil
}

type workspaceWhere[Q psql.Filterable] struct {
	ID   psql.WhereMod[Q, uuid.UUID]
	Name psql.WhereMod[Q, string]
}

func (workspaceWhere[Q]) AliasedAs(alias string) workspaceWhere[Q] {
	return buildWorkspaceWhere[Q](buildWorkspaceColumns(alias))
}

func buildWorkspaceWhere[Q psql.Filterable](cols workspaceColumns) workspaceWhere[Q] {
	return workspaceWhere[Q]{
		ID:   psql.Where[Q, uuid.UUID](cols.ID),
		Name: psql.Where[Q, string](cols.Name),
	}
}

func (o *Workspace) Preload(name string, retrieved any) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Members":
		rels, ok := retrieved.(MemberSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Members = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	case "Projects":
		rels, ok := retrieved.(ProjectSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Projects = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	case "TaskComments":
		rels, ok := retrieved.(TaskCommentSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.TaskComments = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	case "Tasks":
		rels, ok := retrieved.(TaskSlice)
		if !ok {
			return fmt.Errorf("workspace cannot load %T as %q", retrieved, name)
		}

		o.R.Tasks = rels

		for _, rel := range rels {
			if rel != nil {
				rel.R.Workspace = o
			}
		}
		return nil
	default:
		return fmt.Errorf("workspace has no relationship %q", name)
	}
}

type workspacePreloader struct{}

func buildWorkspacePreloader() workspacePreloader {
	return workspacePreloader{}
}

type workspaceThenLoader[Q orm.Loadable] struct {
	Members      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Projects     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tasks        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildWorkspaceThenLoader[Q orm.Loadable]() workspaceThenLoader[Q] {
	type MembersLoadInterface interface {
		LoadMembers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProjectsLoadInterface interface {
		LoadProjects(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskCommentsLoadInterface interface {
		LoadTaskComments(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TasksLoadInterface interface {
		LoadTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return workspaceThenLoader[Q]{
		Members: thenLoadBuilder[Q](
			"Members",
			func(ctx context.Context, exec bob.Executor, retrieved MembersLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadMembers(ctx, exec, mods...)
			},
		),
		Projects: thenLoadBuilder[Q](
			"Projects",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadProjects(ctx, exec, mods...)
			},
		),
		TaskComments: thenLoadBuilder[Q](
			"TaskComments",
			func(ctx context.Context, exec bob.Executor, retrieved TaskCommentsLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTaskComments(ctx, exec, mods...)
			},
		),
		Tasks: thenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksLoadInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadMembers loads the workspace's Members into the .R struct
func (o *Workspace) LoadMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Members = nil

	related, err := o.Members(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Members = related
	return nil
}

// LoadMembers loads the workspace's Members into the .R struct
func (os WorkspaceSlice) LoadMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	members, err := os.Members(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Members = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range members {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Members = append(o.R.Members, rel)
		}
	}

	return nil
}

// LoadProjects loads the workspace's Projects into the .R struct
func (o *Workspace) LoadProjects(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Projects = nil

	related, err := o.Projects(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Projects = related
	return nil
}

// LoadProjects loads the workspace's Projects into the .R struct
func (os WorkspaceSlice) LoadProjects(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	projects, err := os.Projects(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Projects = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range projects {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Projects = append(o.R.Projects, rel)
		}
	}

	return nil
}

// LoadTaskComments loads the workspace's TaskComments into the .R struct
func (o *Workspace) LoadTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.TaskComments = nil

	related, err := o.TaskComments(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.TaskComments = related
	return nil
}

// LoadTaskComments loads the workspace's TaskComments into the .R struct
func (os WorkspaceSlice) LoadTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	taskComments, err := os.TaskComments(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.TaskComments = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range taskComments {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.TaskComments = append(o.R.TaskComments, rel)
		}
	}

	return nil
}

// LoadTasks loads the workspace's Tasks into the .R struct
func (o *Workspace) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	// Reset the relationship
	o.R.Tasks = nil

	related, err := o.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, rel := range related {
		rel.R.Workspace = o
	}

	o.R.Tasks = related
	return nil
}

// LoadTasks loads the workspace's Tasks into the .R struct
func (os WorkspaceSlice) LoadTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	tasks, err := os.Tasks(mods...).All(ctx, exec)
	if err != nil {
		return err
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		o.R.Tasks = nil
	}

	for _, o := range os {
		if o == nil {
			continue
		}

		for _, rel := range tasks {

			if !(o.ID == rel.WorkspaceID) {
				continue
			}

			rel.R.Workspace = o

			o.R.Tasks = append(o.R.Tasks, rel)
		}
	}

	return nil
}

// workspaceC is where relationship counts are stored.
type workspaceC struct {
	Members      *int64 `json:"Members"`
	Projects     *int64 `json:"Projects"`
	TaskComments *int64 `json:"TaskComments"`
	Tasks        *int64 `json:"Tasks"`
}

// PreloadCount sets a count in the C struct by name
func (o *Workspace) PreloadCount(name string, count int64) error {
	if o == nil {
		return nil
	}

	switch name {
	case "Members":
		o.C.Members = &count
	case "Projects":
		o.C.Projects = &count
	case "TaskComments":
		o.C.TaskComments = &count
	case "Tasks":
		o.C.Tasks = &count
	}
	return nil
}

type workspaceCountPreloader struct {
	Members      func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Projects     func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
	Tasks        func(...bob.Mod[*dialect.SelectQuery]) psql.Preloader
}

func buildWorkspaceCountPreloader() workspaceCountPreloader {
	return workspaceCountPreloader{
		Members: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Workspace]("Members", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Workspaces.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Members.Name()),
					sm.Where(psql.Quote(Members.Alias(), "workspace_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Projects: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Workspace]("Projects", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Workspaces.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Projects.Name()),
					sm.Where(psql.Quote(Projects.Alias(), "workspace_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		TaskComments: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Workspace]("TaskComments", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Workspaces.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(TaskComments.Name()),
					sm.Where(psql.Quote(TaskComments.Alias(), "workspace_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
		Tasks: func(mods ...bob.Mod[*dialect.SelectQuery]) psql.Preloader {
			return countPreloader[*Workspace]("Tasks", func(parent string) bob.Expression {
				// Build a correlated subquery: (SELECT COUNT(*) FROM related WHERE fk = parent.pk)
				if parent == "" {
					parent = Workspaces.Alias()
				}

				subqueryMods := []bob.Mod[*dialect.SelectQuery]{
					sm.Columns(psql.Raw("count(*)")),

					sm.From(Tasks.Name()),
					sm.Where(psql.Quote(Tasks.Alias(), "workspace_id").EQ(psql.Quote(parent, "id"))),
				}
				subqueryMods = append(subqueryMods, mods...)
				return psql.Group(psql.Select(subqueryMods...).Expression)
			})
		},
	}
}

type workspaceCountThenLoader[Q orm.Loadable] struct {
	Members      func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Projects     func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	TaskComments func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
	Tasks        func(...bob.Mod[*dialect.SelectQuery]) orm.Loader[Q]
}

func buildWorkspaceCountThenLoader[Q orm.Loadable]() workspaceCountThenLoader[Q] {
	type MembersCountInterface interface {
		LoadCountMembers(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type ProjectsCountInterface interface {
		LoadCountProjects(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TaskCommentsCountInterface interface {
		LoadCountTaskComments(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}
	type TasksCountInterface interface {
		LoadCountTasks(context.Context, bob.Executor, ...bob.Mod[*dialect.SelectQuery]) error
	}

	return workspaceCountThenLoader[Q]{
		Members: countThenLoadBuilder[Q](
			"Members",
			func(ctx context.Context, exec bob.Executor, retrieved MembersCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountMembers(ctx, exec, mods...)
			},
		),
		Projects: countThenLoadBuilder[Q](
			"Projects",
			func(ctx context.Context, exec bob.Executor, retrieved ProjectsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountProjects(ctx, exec, mods...)
			},
		),
		TaskComments: countThenLoadBuilder[Q](
			"TaskComments",
			func(ctx context.Context, exec bob.Executor, retrieved TaskCommentsCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTaskComments(ctx, exec, mods...)
			},
		),
		Tasks: countThenLoadBuilder[Q](
			"Tasks",
			func(ctx context.Context, exec bob.Executor, retrieved TasksCountInterface, mods ...bob.Mod[*dialect.SelectQuery]) error {
				return retrieved.LoadCountTasks(ctx, exec, mods...)
			},
		),
	}
}

// LoadCountMembers loads the count of Members into the C struct
func (o *Workspace) LoadCountMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Members(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Members = &count
	return nil
}

// LoadCountMembers loads the count of Members for a slice
func (os WorkspaceSlice) LoadCountMembers(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountMembers(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

// LoadCountProjects loads the count of Projects into the C struct
func (o *Workspace) LoadCountProjects(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Projects(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Projects = &count
	return nil
}

// LoadCountProjects loads the count of Projects for a slice
func (os WorkspaceSlice) LoadCountProjects(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountProjects(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

// LoadCountTaskComments loads the count of TaskComments into the C struct
func (o *Workspace) LoadCountTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.TaskComments(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.TaskComments = &count
	return nil
}

// LoadCountTaskComments loads the count of TaskComments for a slice
func (os WorkspaceSlice) LoadCountTaskComments(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountTaskComments(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

// LoadCountTasks loads the count of Tasks into the C struct
func (o *Workspace) LoadCountTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if o == nil {
		return nil
	}

	count, err := o.Tasks(mods...).Count(ctx, exec)
	if err != nil {
		return err
	}

	o.C.Tasks = &count
	return nil
}

// LoadCountTasks loads the count of Tasks for a slice
func (os WorkspaceSlice) LoadCountTasks(ctx context.Context, exec bob.Executor, mods ...bob.Mod[*dialect.SelectQuery]) error {
	if len(os) == 0 {
		return nil
	}

	for _, o := range os {
		if err := o.LoadCountTasks(ctx, exec, mods...); err != nil {
			return err
		}
	}

	return nil
}

type workspaceJoins[Q dialect.Joinable] struct {
	typ          string
	Members      modAs[Q, memberColumns]
	Projects     modAs[Q, projectColumns]
	TaskComments modAs[Q, taskCommentColumns]
	Tasks        modAs[Q, taskColumns]
}

func (j workspaceJoins[Q]) aliasedAs(alias string) workspaceJoins[Q] {
	return buildWorkspaceJoins[Q](buildWorkspaceColumns(alias), j.typ)
}

func buildWorkspaceJoins[Q dialect.Joinable](cols workspaceColumns, typ string) workspaceJoins[Q] {
	return workspaceJoins[Q]{
		typ: typ,
		Members: modAs[Q, memberColumns]{
			c: Members.Columns,
			f: func(to memberColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Members.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Projects: modAs[Q, projectColumns]{
			c: Projects.Columns,
			f: func(to projectColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Projects.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		TaskComments: modAs[Q, taskCommentColumns]{
			c: TaskComments.Columns,
			f: func(to taskCommentColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, TaskComments.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
		Tasks: modAs[Q, taskColumns]{
			c: Tasks.Columns,
			f: func(to taskColumns) bob.Mod[Q] {
				mods := make(mods.QueryMods[Q], 0, 1)

				{
					mods = append(mods, dialect.Join[Q](typ, Tasks.Name().As(to.Alias())).On(
						to.WorkspaceID.EQ(cols.ID),
					))
				}

				return mods
			},
		},
	}
}
