// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

import (
	"context"
	"errors"
	"testing"

	"github.com/stephenafamo/bob"
	models "github.com/tak848/lxgo4-bob/internal/infra/dbgen"
	factory "github.com/tak848/lxgo4-bob/internal/infra/dbgen/factory"
)

func TestTaskUniqueConstraintErrors(t *testing.T) {
	if testDB == nil {
		t.Skip("No database connection provided")
	}

	f := factory.New()
	tests := []struct {
		name         string
		expectedErr  *UniqueConstraintError
		conflictMods func(context.Context, *testing.T, bob.Executor, *models.Task) factory.TaskModSlice
	}{
		{
			name:        "ErrUniqueTasksPkey",
			expectedErr: TaskErrors.ErrUniqueTasksPkey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.Task) factory.TaskModSlice {
				shouldUpdate := false
				updateMods := make(factory.TaskModSlice, 0, 1)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewTaskWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.TaskModSlice{
					factory.TaskMods.ID(obj.ID),
				}
			},
		},
		{
			name:        "ErrUniqueTasksWorkspaceIdIdKey",
			expectedErr: TaskErrors.ErrUniqueTasksWorkspaceIdIdKey,
			conflictMods: func(ctx context.Context, t *testing.T, exec bob.Executor, obj *models.Task) factory.TaskModSlice {
				shouldUpdate := false
				updateMods := make(factory.TaskModSlice, 0, 2)

				if shouldUpdate {
					if err := obj.Update(ctx, exec, f.NewTaskWithContext(ctx, updateMods...).BuildSetter()); err != nil {
						t.Fatalf("Error updating object: %v", err)
					}
				}

				return factory.TaskModSlice{
					factory.TaskMods.WorkspaceID(obj.WorkspaceID),
					factory.TaskMods.ID(obj.ID),
				}
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			ctx, cancel := context.WithCancel(t.Context())
			t.Cleanup(cancel)

			tx, err := testDB.Begin(ctx)
			if err != nil {
				t.Fatalf("Couldn't start database transaction: %v", err)
			}

			defer func() {
				if err := tx.Rollback(ctx); err != nil {
					t.Fatalf("Error rolling back transaction: %v", err)
				}
			}()

			var exec bob.Executor = tx

			obj, err := f.NewTaskWithContext(ctx, factory.TaskMods.WithParentsCascading()).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			obj2, err := f.NewTaskWithContext(ctx).Create(ctx, exec)
			if err != nil {
				t.Fatal(err)
			}

			err = obj2.Update(ctx, exec, f.NewTaskWithContext(ctx, tt.conflictMods(ctx, t, exec, obj)...).BuildSetter())
			if !errors.Is(ErrUniqueConstraint, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !errors.Is(tt.expectedErr, err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
			if !ErrUniqueConstraint.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.name, err)
			}
			if !tt.expectedErr.Is(err) {
				t.Fatalf("Expected: %s, Got: %v", tt.expectedErr.Error(), err)
			}
		})
	}
}
