// Code generated by BobGen psql v0.42.1-0.20260305085859-d9c40b0abedd. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dberrors

var TaskCommentErrors = &taskCommentErrors{
	ErrUniqueTaskCommentsPkey: &UniqueConstraintError{
		schema:  "",
		table:   "task_comments",
		columns: []string{"id"},
		s:       "task_comments_pkey",
	},

	ErrUniqueTaskCommentsWorkspaceIdIdKey: &UniqueConstraintError{
		schema:  "",
		table:   "task_comments",
		columns: []string{"workspace_id", "id"},
		s:       "task_comments_workspace_id_id_key",
	},
}

type taskCommentErrors struct {
	ErrUniqueTaskCommentsPkey *UniqueConstraintError

	ErrUniqueTaskCommentsWorkspaceIdIdKey *UniqueConstraintError
}
